% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={JASP Verificiation Project},
  pdfauthor={Jonas Petter},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage[]{natbib}
\bibliographystyle{apalike}

\title{JASP Verificiation Project}
\author{Jonas Petter}
\date{2020-09-23}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{introduction}{%
\chapter{Introduction}\label{introduction}}

\hypertarget{the-project}{%
\section{The Project}\label{the-project}}

This document contains the verification of the results computed in JASP. For this purpose, the same statistical tests have been performed on the same datasets, using the most popular statistical software packages and hand calculations. The comparison of the output is available for each test in the following chapters.

The software packages that have been used for comparison are:

\begin{tabular}{ll}
\toprule
Software & Version\\
\midrule
JASP & 0.13.1\\
SPSS & 26.0.0\\
SAS & 3.8 (Basic Edition)\\
Minitab & 19.2020.1\\
R & 4.0.2\\
\bottomrule
\end{tabular}

All code used for computation is available in this document. The datasets used can be found in the Github repository of this project: {[}URL OF THE PROJECT AS SOON AS IT IS PUBLISHED{]}

\hypertarget{bibliography}{%
\section{Bibliography}\label{bibliography}}

Field, A. (2018). \emph{Discovering statistics using IBM SPSS statistics}. Los Angeles, CA: SAGE.

Freeman, E., Heathcote, A., Chalmers, K., \& Hockley, W. (2010). Item effects in recognition memory for words. \emph{Journal of Memory and Language, 62}(1), 1-18.

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

Kerlinger, F. N. (1969). \emph{Foundations of behavioral research}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{descriptives}{%
\chapter{Descriptives}\label{descriptives}}

\hypertarget{descriptives-1}{%
\section{Descriptives}\label{descriptives-1}}

An example from Kerlinger (1969, pp.~93-95):

\begin{table}

\caption{\label{tab:unnamed-chunk-3}Data for Descriptives}
\centering
\begin{tabular}[t]{r}
\toprule
Data\\
\midrule
1\\
2\\
3\\
4\\
5\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview}{%
\subsection{Results Overview}\label{results-overview}}

\begin{table}

\caption{\label{tab:unnamed-chunk-4}Result Overview Descriptives}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
Mean & 3.0 & 3.000 & 3.000 & 3.000 & 3.000 & 3.000\\
Variance & 2.5 & 2.500 & 2.500 & 2.500 & 2.500 & 2.500\\
Median & NA & 3.000 & 3.000 & 3.000 & 3.000 & 3.000\\
Standard Deviation & NA & 1.580 & 1.580 & 1.580 & 1.580 & 1.580\\
SE(Mean) & NA & 0.707 & 0.707 & 0.707 & 0.707 & 0.707\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand}{%
\subsection{By Hand}\label{by-hand}}

Calculations by hand can be found in Kerlinger (1969, pp.~93-95).

Result:

Mean = 3

Variance = 2.5

\textbf{Note}: Kerlinger calculated the population variance, however as all statistical software computes the sample variance, the formula was adapted accordingly to be divided by N-1.

\hypertarget{jasp}{%
\subsection{JASP}\label{jasp}}

\begin{figure}[!h]
\includegraphics{Screenshots/Descriptives/DescriptivesJASP} \caption{\label{fig:descJASP}JASP Output for Descriptives}\label{fig:descJASP}
\end{figure}

\hypertarget{spss}{%
\subsection{SPSS}\label{spss}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{DESCRIPTIVES VARIABLES=Data}
  \OperatorTok{/}\NormalTok{STATISTICS=MEAN STDDEV VARIANCE MIN MAX SEMEAN.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Descriptives/DescriptivesSPSS} \caption{\label{fig:descSPSS}SPSS Output for Descriptives}\label{fig:descSPSS}
\end{figure}

\hypertarget{sas}{%
\subsection{SAS}\label{sas}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC MEANS DATA=work.Desc Mean STDDEV Median STDERR Var;}
\NormalTok{  VAR Data;}
\NormalTok{RUN;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Descriptives/DescriptivesSAS} \caption{\label{fig:descSAS}SAS Output for Descriptives}\label{fig:descSAS}
\end{figure}

\hypertarget{minitab}{%
\subsection{Minitab}\label{minitab}}

\begin{figure}[!h]
\includegraphics{Screenshots/Descriptives/DescriptivesMinitab} \caption{\label{fig:descMinitb}Minitab Output for Descriptives}\label{fig:descMinitab}
\end{figure}

\hypertarget{r}{%
\subsection{R}\label{r}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(desc.data2}\OperatorTok{$}\NormalTok{Data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sd}\NormalTok{(desc.data2}\OperatorTok{$}\NormalTok{Data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.581139
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{var}\NormalTok{(desc.data2}\OperatorTok{$}\NormalTok{Data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{median}\NormalTok{(desc.data2}\OperatorTok{$}\NormalTok{Data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{se <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x) }\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{var}\NormalTok{(x)}\OperatorTok{/}\KeywordTok{length}\NormalTok{(x))}
\KeywordTok{se}\NormalTok{(desc.data2}\OperatorTok{$}\NormalTok{Data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7071068
\end{verbatim}

\hypertarget{remarks}{%
\subsection{Remarks}\label{remarks}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references}{%
\subsection{References}\label{references}}

Kerlinger, F. N. (1969). \emph{Foundations of behavioral research}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{t-tests}{%
\chapter{T-Tests}\label{t-tests}}

\hypertarget{independent-samples-t-test}{%
\section{Independent Samples T-Test}\label{independent-samples-t-test}}

An example from Hays (1974, pp.~404-407):

"An experimenter working in the area of motivational factors in perception was interested in the effects of deprivation upon the perceived size of objects. Among the studies carried out was one done with orphans, who were compared with nonorphaned children on the basis of the judged size of parental figures viewed at a distance. {[}\ldots{]}Now two independent randomly selected groups were used. Sample 1 was a group of orphaned children without foster parents. Sample 2 was a group of children having a normal family with both parents. Both population of children sampled showed the same age level, sex distribution, educational level, and so forth. The question asked by the experimenter was `Do deprived children tend to judge the parental figures relatively larger than do the nondeprived?' In terms of a null and alternative hypothesis,

H\textsubscript{0}: \(\mu\)\textsubscript{1} - \(\mu\)\textsubscript{2} \(\le 0\)

H\textsubscript{1}: \(\mu\)\textsubscript{1} - \(\mu\)\textsubscript{2} \(> 0\).

The \(\alpha\) level for significance decided upon was .05. The actual results were

\emph{Sample 1:}

M\textsubscript{1} = 1.8

\textsubscript{S1} = .7

N\textsubscript{1} = 125

\emph{Sample 2:}

M\textsubscript{2} = 1.6

\textsubscript{S2} = .9

N\textsubscript{2} = 150"

\textbf{Note}: A data set with these properties has been simulated using R.

\hypertarget{results-overview}{%
\subsection{Results Overview}\label{results-overview}}

\begin{table}

\caption{\label{tab:unnamed-chunk-9}Result Overview Independent Samples T-Test}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
t (Welch) & 2.11 & 2.0717 & 2.072 & 2.07 & 2.07 & 2.0717\\
t (Student) & NA & 2.0257 & 2.026 & 2.03 & 2.03 & 2.0257\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand}{%
\subsection{By Hand}\label{by-hand}}

Calculations by hand can be found in Hays, 1974, pp.~404-407.

Result: t = 2.11

Significant (two-tailed test) for \(\alpha\) = .05 or less

\textbf{Note:} Hays calculated only the Welch T-test.

\hypertarget{jasp}{%
\subsection{JASP}\label{jasp}}

\begin{figure}[!h]
\includegraphics{Screenshots/Independent Samples T test/isttJASP} \caption{\label{fig:isttJASP}JASP Output for Independent Samples T-Test}\label{fig:isttJASP}
\end{figure}

\hypertarget{spss}{%
\subsection{SPSS}\label{spss}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{T}\OperatorTok{-}\NormalTok{TEST GROUPS=}\KeywordTok{groups}\NormalTok{(}\DecValTok{1} \DecValTok{2}\NormalTok{)}
  \OperatorTok{/}\NormalTok{MISSING=ANALYSIS}
  \OperatorTok{/}\NormalTok{VARIABLES=samples}
  \OperatorTok{/}\NormalTok{CRITERIA=}\KeywordTok{CI}\NormalTok{(.}\DecValTok{95}\NormalTok{).}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Independent Samples T test/isttSPSS} \caption{\label{fig:isttSPSS}SPSS Output for Independent Samples T-Test}\label{fig:isttSPSS}
\end{figure}

\hypertarget{sas}{%
\subsection{SAS}\label{sas}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{proc ttest data=istt sides=}\DecValTok{2}\NormalTok{ alpha=}\FloatTok{0.05}\NormalTok{ h0=}\DecValTok{0}\NormalTok{;}
\NormalTok{ 	title }\StringTok{"Two sample t-test"}\NormalTok{;}
\NormalTok{ 	class Group; }
\NormalTok{	var Score;}
\NormalTok{   run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Independent Samples T test/isttSAS} \caption{\label{fig:isttSAS}SAS Output for Independent Samples T-Test}\label{fig:isttSAS}
\end{figure}

\hypertarget{minitab}{%
\subsection{Minitab}\label{minitab}}

\begin{figure}[!h]
\includegraphics{Screenshots/Independent Samples T test/isttMinitab} \caption{\label{fig:isttMinitab}Minitab Output for Welch Independent Samples T-Test}\label{fig:isttMinitab}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Independent Samples T test/isttMinitab2} \caption{\label{fig:isttMinitab2}Minitab Output for Student Independent Samples T-Test}\label{fig:isttMinitab2}
\end{figure}

\hypertarget{r}{%
\subsection{R}\label{r}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(}\KeywordTok{subset}\NormalTok{(istt.data, Group }\OperatorTok{==}\StringTok{ }\DecValTok{1}\NormalTok{)}\OperatorTok{$}\NormalTok{Score, }\KeywordTok{subset}\NormalTok{(istt.data, Group }\OperatorTok{==}\StringTok{ }\DecValTok{2}\NormalTok{)}\OperatorTok{$}\NormalTok{Score)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 	Welch Two Sample t-test
## 
## data:  subset(istt.data, Group == 1)$Score and subset(istt.data, Group == 2)$Score
## t = 2.0717, df = 271.76, p-value = 0.03924
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.009938365 0.390061635
## sample estimates:
## mean of x mean of y 
##       1.8       1.6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(}\KeywordTok{subset}\NormalTok{(istt.data, Group }\OperatorTok{==}\StringTok{ }\DecValTok{1}\NormalTok{)}\OperatorTok{$}\NormalTok{Score, }\KeywordTok{subset}\NormalTok{(istt.data, Group }\OperatorTok{==}\StringTok{ }\DecValTok{2}\NormalTok{)}\OperatorTok{$}\NormalTok{Score, }\DataTypeTok{var.equal =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 	Two Sample t-test
## 
## data:  subset(istt.data, Group == 1)$Score and subset(istt.data, Group == 2)$Score
## t = 2.0257, df = 273, p-value = 0.04377
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.005624928 0.394375072
## sample estimates:
## mean of x mean of y 
##       1.8       1.6
\end{verbatim}

\hypertarget{remarks}{%
\subsection{Remarks}\label{remarks}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references}{%
\subsection{References}\label{references}}

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{mann-whitney-test}{%
\section{Mann-Whitney Test}\label{mann-whitney-test}}

An example from Hays (1974, pp.~778-780):

``As an example, consider the following data:''

\begin{table}

\caption{\label{tab:unnamed-chunk-15}Data for Mann-Whitney Test}
\centering
\begin{tabular}[t]{rl}
\toprule
Score & Group\\
\midrule
8 & A\\
3 & A\\
4 & A\\
6 & A\\
1 & B\\
\addlinespace
7 & B\\
9 & B\\
10 & B\\
12 & B\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview-1}{%
\subsection{Results Overview}\label{results-overview-1}}

\begin{table}

\caption{\label{tab:unnamed-chunk-16}Result Overview Mann-Whitney Test}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
U' & 5 & 5 & 5 & 5 & 5 & 5\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand-1}{%
\subsection{By Hand}\label{by-hand-1}}

Calculations by hand can be found in Hays, 1974, pp.~778-780.

Result:

U' = 5

U = 15

Not significant for \(\alpha\) = .05 or less.

\hypertarget{jasp-1}{%
\subsection{JASP}\label{jasp-1}}

\begin{figure}[!h]
\includegraphics{Screenshots/Mann WHitney/mwtJASP} \caption{\label{fig:mwtJASP}JASP Output for Mann-Whitney Test}\label{fig:mwtJASP}
\end{figure}

\textbf{Note:} W corresponds to U' in the hand calculation.

\hypertarget{spss-1}{%
\subsection{SPSS}\label{spss-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\OperatorTok{*}\NormalTok{Nonparametric Tests}\OperatorTok{:}\StringTok{ }\NormalTok{Independent Samples. }
\NormalTok{NPTESTS }
  \OperatorTok{/}\NormalTok{INDEPENDENT }\KeywordTok{TEST}\NormalTok{ (Score) }\KeywordTok{GROUP}\NormalTok{ (Group) MANN_WHITNEY }
  \OperatorTok{/}\NormalTok{MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE}
  \OperatorTok{/}\NormalTok{CRITERIA ALPHA=}\FloatTok{0.05}\NormalTok{  CILEVEL=}\FloatTok{95.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Mann WHitney/mwtSPSS} \caption{\label{fig:mwtSPSS}SPSS Output for Mann-Whitney Test}\label{fig:mwtSPSS}
\end{figure}

\textbf{Note:} U = 15 corresponds to U' = 5.

\hypertarget{sas-1}{%
\subsection{SAS}\label{sas-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC npar1way data=work.mwt wilcoxon;}
\NormalTok{class Group;}
\NormalTok{var Score;}
\NormalTok{run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Mann WHitney/mwtSAS} \caption{\label{fig:mwtSAS}SAS Output for Mann-Whitney Test}\label{fig:mwtSAS}
\end{figure}

\textbf{Note:} U = 15 corresponds to U' = 5.

\hypertarget{minitab-1}{%
\subsection{Minitab}\label{minitab-1}}

\begin{figure}[!h]
\includegraphics{Screenshots/Mann WHitney/mwtMinitab} \caption{\label{fig:mwtMinitab}Minitab Output for Mann-Whitney Test}\label{fig:mwtMinitab}
\end{figure}

\textbf{Note:} W corresponds to U in the hand calculation and U = 15 corresponds to U' = 5.

\hypertarget{r-1}{%
\subsection{R}\label{r-1}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{wilcox.test}\NormalTok{(Score}\OperatorTok{~}\NormalTok{Group, }\DataTypeTok{data =}\NormalTok{ MWT.data2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 	Wilcoxon rank sum exact test
## 
## data:  Score by Group
## W = 5, p-value = 0.2857
## alternative hypothesis: true location shift is not equal to 0
\end{verbatim}

\textbf{Note:} W corresponds to U' in the hand calculation.

\hypertarget{remarks-1}{%
\subsection{Remarks}\label{remarks-1}}

All differences in results between the software and hand calculation are due to rounding.

The output for the Mann-Whitney test is not clearly defined, leading to different conventions in different software. The R documentation explains it as follows:

``The two most common definitions correspond to the sum of the ranks of the first sample with the minimum value subtracted or not: R subtracts and S-PLUS does not, giving a value which is larger by m(m+1)/2 for a first sample of size m. (It seems Wilcoxon's original paper used the unadjusted sum of the ranks but subsequent tables subtracted the minimum.) R's value can also be computed as the number of all pairs (x{[}i{]}, y{[}j{]}) for which y{[}j{]} is not greater than x{[}i{]}, the most common definition of the Mann-Whitney test.''

\hypertarget{references-1}{%
\subsection{References}\label{references-1}}

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{paired-samples-t-test}{%
\section{Paired Samples T-Test}\label{paired-samples-t-test}}

An example from Hays (1974, pp.~424-427):

``Consider once again the question of scores on a test of dominance. The basic question has to do with the mean score for men as opposed to the mean score for women. In carrying out the experiment, the investigator decided to sample eight husband-wife-pairs at random. The members of each pair were given the test of dominance separately, and the data turned out as follows:''

\begin{table}

\caption{\label{tab:unnamed-chunk-21}Data for Paired Sample T-Test}
\centering
\begin{tabular}[t]{rr}
\toprule
Husband & Wife\\
\midrule
26 & 30\\
28 & 29\\
28 & 28\\
29 & 27\\
30 & 26\\
\addlinespace
31 & 25\\
34 & 24\\
37 & 23\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview-2}{%
\subsection{Results Overview}\label{results-overview-2}}

\begin{table}

\caption{\label{tab:unnamed-chunk-22}Result Overview Paired Samples T-Test}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
t & 1.838 & 1.8381 & 1.838 & 1.84 & 1.84 & 1.8381\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand-2}{%
\subsection{By Hand}\label{by-hand-2}}

Calculations by hand can be found in Hays, 1974, pp.~424-427.

Result: t = 1.838

Not significant (two-tailed test) for \(\alpha\) = .05 or less
\#\#\# JASP

\begin{figure}[!h]
\includegraphics{Screenshots/Paired Samples T test/psttJASP} \caption{\label{fig:psttJASP}JASP Output for Paired Samples T-Test}\label{fig:psttJASP}
\end{figure}

\hypertarget{spss-2}{%
\subsection{SPSS}\label{spss-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{T}\OperatorTok{-}\NormalTok{TEST PAIRS=Husband WITH }\KeywordTok{Wife}\NormalTok{ (PAIRED)}
  \OperatorTok{/}\NormalTok{CRITERIA=}\KeywordTok{CI}\NormalTok{(.}\DecValTok{9500}\NormalTok{)}
  \OperatorTok{/}\NormalTok{MISSING=ANALYSIS.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Paired Samples T test/psttSPSS} \caption{\label{fig:psttSPSS}SPSS Output for Paired Samples T-Test}\label{fig:psttSPSS}
\end{figure}

\hypertarget{sas-2}{%
\subsection{SAS}\label{sas-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{proc ttest data=pstt sides=}\DecValTok{2}\NormalTok{ alpha=}\FloatTok{0.05}\NormalTok{ h0=}\DecValTok{0}\NormalTok{;}
\NormalTok{title }\StringTok{"Paired sample t-test"}\NormalTok{;}
\NormalTok{paired Husband }\OperatorTok{*}\StringTok{ }\NormalTok{Wife;}
\NormalTok{run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Paired Samples T test/psttSAS} \caption{\label{fig:psttSAS}SAS Output for Paired Samples T-Test}\label{fig:psttSAS}
\end{figure}

\hypertarget{minitab-2}{%
\subsection{Minitab}\label{minitab-2}}

\begin{figure}[!h]
\includegraphics{Screenshots/Paired Samples T test/psttMinitab} \caption{\label{fig:psttMinitab}Minitab Output for Paired Samples T-Test}\label{fig:psttMinitab}
\end{figure}

\hypertarget{r-2}{%
\subsection{R}\label{r-2}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(pstt.data}\OperatorTok{$}\NormalTok{Husband, pstt.data}\OperatorTok{$}\NormalTok{Wife, }\DataTypeTok{paired =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 	Paired t-test
## 
## data:  pstt.data$Husband and pstt.data$Wife
## t = 1.8381, df = 7, p-value = 0.1086
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.109927  8.859927
## sample estimates:
## mean of the differences 
##                   3.875
\end{verbatim}

\hypertarget{remarks-2}{%
\subsection{Remarks}\label{remarks-2}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{wilcoxon-test}{%
\section{Wilcoxon Test}\label{wilcoxon-test}}

An example from Hays (1974, pp.~780-781):

``Suppose that in some experiment involving a single treatment and one control group, subjects were first matched pairwise, and then one member of each pair was assigned to the experimental group at random. In the experiment proper, each subject received some Y score.''

\begin{table}

\caption{\label{tab:unnamed-chunk-27}Data for Wilcoxon Test}
\centering
\begin{tabular}[t]{rr}
\toprule
Treatment. & Control\\
\midrule
83 & 75\\
80 & 78\\
81 & 66\\
74 & 77\\
79 & 80\\
\addlinespace
78 & 68\\
72 & 75\\
84 & 90\\
85 & 81\\
88 & 83\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview-3}{%
\subsection{Results Overview}\label{results-overview-3}}

\begin{table}

\caption{\label{tab:unnamed-chunk-28}Result Overview Wilcoxon Test}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
W' & 15 & 15 & 15 & NA & 15 & 15\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand-3}{%
\subsection{By Hand}\label{by-hand-3}}

Calculations by hand can be found in Hays, 1974, pp.~780-781.

Result:

T = 15

Not significant for \(\alpha\) = .05 or less.

\hypertarget{jasp-2}{%
\subsection{JASP}\label{jasp-2}}

\begin{figure}[!h]
\includegraphics{Screenshots/Wilcoxon Test/WilcoxonJASP} \caption{\label{fig:WilcoxonJASP}JASP Output for Wilcoxon Test}\label{fig:WilcoxonJASP}
\end{figure}

\hypertarget{spss-3}{%
\subsection{SPSS}\label{spss-3}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\OperatorTok{*}\NormalTok{Nonparametric Tests}\OperatorTok{:}\StringTok{ }\NormalTok{Related Samples. }
\NormalTok{NPTESTS }
  \OperatorTok{/}\NormalTok{RELATED }\KeywordTok{TEST}\NormalTok{(Treatment Control) WILCOXON }
  \OperatorTok{/}\NormalTok{MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE}
  \OperatorTok{/}\NormalTok{CRITERIA ALPHA=}\FloatTok{0.05}\NormalTok{  CILEVEL=}\FloatTok{95.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Wilcoxon Test/WilcoxonSPSS} \caption{\label{fig:WilcoxonSPSS}SPSS Output for Wilcoxon Test}\label{fig:WilcoxonSPSS}
\end{figure}

\hypertarget{sas-3}{%
\subsection{SAS}\label{sas-3}}

Not available in SAS.

\hypertarget{minitab-3}{%
\subsection{Minitab}\label{minitab-3}}

\begin{figure}[!h]
\includegraphics{Screenshots/Wilcoxon Test/WilcoxonMinitab} \caption{\label{fig:WilcoxonMinitab}Minitab Output for Wilcoxon Test}\label{fig:WilcoxonMinitab}
\end{figure}

\hypertarget{r-3}{%
\subsection{R}\label{r-3}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{wilcox.test}\NormalTok{(Wilcoxon.data2}\OperatorTok{$}\NormalTok{Control, Wilcoxon.data2}\OperatorTok{$}\NormalTok{Treatment., }\DataTypeTok{paired =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in wilcox.test.default(Wilcoxon.data2$Control,
## Wilcoxon.data2$Treatment., : cannot compute exact p-value with ties
\end{verbatim}

\begin{verbatim}
## 
## 	Wilcoxon signed rank test with continuity correction
## 
## data:  Wilcoxon.data2$Control and Wilcoxon.data2$Treatment.
## V = 15, p-value = 0.221
## alternative hypothesis: true location shift is not equal to 0
\end{verbatim}

\hypertarget{remarks-3}{%
\subsection{Remarks}\label{remarks-3}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references-2}{%
\subsection{References}\label{references-2}}

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{one-sample-t-test}{%
\section{One Sample T-Test}\label{one-sample-t-test}}

A dataset with the following properties has been generated using R:

n = 100

M = 5

\(\sigma\) = 1

The expected mean to perform the One Sample T-test against is:

E(M) = 3

The alpha level was chosen to be:

\(\alpha\) = .05

\hypertarget{results-overview-4}{%
\subsection{Results Overview}\label{results-overview-4}}

\begin{table}

\caption{\label{tab:unnamed-chunk-32}Result Overview One Sample T-Test}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
t & 20 & 20 & 20 & 20 & 20 & 20\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand-4}{%
\subsection{By Hand}\label{by-hand-4}}

t = \(\frac{M - E(M) }{\sigma/\sqrt{n}}\)

therefore:

t = \(\frac{5-3}{1/\sqrt{100}}\) = \(\frac{2}{1/10}\) = 20

A t-score of 20 is significant for a two tailed test at \(\alpha\) = .05 or less.

\hypertarget{jasp-3}{%
\subsection{JASP}\label{jasp-3}}

\begin{figure}[!h]
\includegraphics{Screenshots/One Sample T test/osttJASP} \caption{\label{fig:osttJASP}JASP Output for One Sample T-Test}\label{fig:osttJASP}
\end{figure}

\hypertarget{spss-4}{%
\subsection{SPSS}\label{spss-4}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{T}\OperatorTok{-}\NormalTok{TEST}
  \OperatorTok{/}\NormalTok{TESTVAL=}\DecValTok{3}
  \OperatorTok{/}\NormalTok{MISSING=ANALYSIS}
  \OperatorTok{/}\NormalTok{VARIABLES=V1}
  \OperatorTok{/}\NormalTok{CRITERIA=}\KeywordTok{CI}\NormalTok{(.}\DecValTok{95}\NormalTok{).}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/One Sample T test/osttSPSS} \caption{\label{fig:osttSPSS}SPSS Output for One Sample T-Test}\label{fig:osttSPSS}
\end{figure}

\hypertarget{sas-4}{%
\subsection{SAS}\label{sas-4}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{proc ttest data=work.OSTT sides=}\DecValTok{2}\NormalTok{ alpha=}\FloatTok{0.05}\NormalTok{  h0=}\DecValTok{3}\NormalTok{;}
\NormalTok{      var Data;}
\NormalTok{   run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/One Sample T test/osttSAS} \caption{\label{fig:osttSAS}SAS Output for One Sample T-Test}\label{fig:osttSAS}
\end{figure}

\hypertarget{minitab-4}{%
\subsection{Minitab}\label{minitab-4}}

\begin{figure}[!h]
\includegraphics{Screenshots/One Sample T test/osttMinitab} \caption{\label{fig:osttMinitab}Minitab Output for One Sample T-Test}\label{fig:osttMinitab}
\end{figure}

\hypertarget{r-4}{%
\subsection{R}\label{r-4}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(ostt.data2}\OperatorTok{$}\NormalTok{V1, }\DataTypeTok{mu =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 	One Sample t-test
## 
## data:  ostt.data2$V1
## t = 20, df = 99, p-value < 2.2e-16
## alternative hypothesis: true mean is not equal to 3
## 95 percent confidence interval:
##  4.801578 5.198422
## sample estimates:
## mean of x 
##         5
\end{verbatim}

\hypertarget{remarks-4}{%
\subsection{Remarks}\label{remarks-4}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{anova}{%
\chapter{ANOVA}\label{anova}}

\hypertarget{one-way-independent-anova}{%
\section{One-Way Independent ANOVA}\label{one-way-independent-anova}}

An example from Hays (1974, pp.~476-478):

"An experiment was carried out to study the effect of a small lesion introduced into a particular structure in a rat's brain on his ability to perform in a discrimination problem. The particular structure studied is bilaterally symmetric. so that the lesion could be introduced into the structure on the right side of the brain, the left side, both sides, or neither side (a control group). Four groups of randomly selected rats were formed, and given the various treatments.{[}\ldots{]} After a period of postoperative recovery, each rats was given the same series of discrimination problems. The dependent variable score was the average number of trials it took each rat to learn the task to some criterion level. The null hypothesis was that the four treatment populations of rats are identical in their average ability to learn this task:

H\textsubscript{0}: \(\mu\)\textsubscript{1} = \(\mu\)\textsubscript{2} = \(\mu\)\textsubscript{3} = \(\mu\)\textsubscript{4}

as against the hypothesis that treatment differences exist:

H\textsubscript{1}: not H\textsubscript{0}.

The alpha level chosen for the experiment was .05."

\begin{table}

\caption{\label{tab:unnamed-chunk-37}Data for One-Way Independent ANOVA}
\centering
\begin{tabular}[t]{rl}
\toprule
Score & Group\\
\midrule
20 & 1\\
18 & 1\\
26 & 1\\
19 & 1\\
26 & 1\\
\addlinespace
24 & 1\\
26 & 1\\
24 & 2\\
22 & 2\\
25 & 2\\
\addlinespace
25 & 2\\
20 & 2\\
21 & 2\\
34 & 2\\
18 & 2\\
\addlinespace
32 & 2\\
23 & 2\\
22 & 2\\
20 & 3\\
22 & 3\\
\addlinespace
30 & 3\\
27 & 3\\
22 & 3\\
24 & 3\\
28 & 3\\
\addlinespace
21 & 3\\
23 & 3\\
25 & 3\\
18 & 3\\
30 & 3\\
\addlinespace
32 & 3\\
27 & 4\\
35 & 4\\
18 & 4\\
24 & 4\\
\addlinespace
28 & 4\\
32 & 4\\
16 & 4\\
18 & 4\\
25 & 4\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview}{%
\subsection{Results Overview}\label{results-overview}}

\begin{table}

\caption{\label{tab:unnamed-chunk-38}Result Overview One-Way Independent ANOVA}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
F & 0.307377 & 0.3082 & 0.308 & 0.31 & 0.31 & 0.308\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand}{%
\subsection{By Hand}\label{by-hand}}

Calculations by hand can be found in Hays, 1974, pp.~476-478.

Results:

\begin{table}

\caption{\label{tab:unnamed-chunk-39}Result from Hays (1974)}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
Source & SS & df & MS & F\\
\midrule
Treatments (between groups) & 22.6 & 3 & 7.5 & 0.307377\\
Error (within groups) & 878.9 & 36 & 24.4 & NA\\
Totals & 901.5 & 39 & NA & NA\\
\bottomrule
\end{tabular}
\end{table}

\textbf{Conclusion:} The null hypothesis cannot be rejected, because the critical F value was 2.84.

\textbf{Note}: Hays reported F =\(\frac{7.5}{24.4}\). For a better comparison we transformed it to a decimal number.

\hypertarget{jasp}{%
\subsection{JASP}\label{jasp}}

\begin{figure}[!h]
\includegraphics{Screenshots/ANOVA/anovaJASP} \caption{\label{fig:anovaJASP}JASP Output for One-Way Independent ANOVA}\label{fig:anovaJASP}
\end{figure}

\hypertarget{spss}{%
\subsection{SPSS}\label{spss}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{ONEWAY Score BY Group}
  \OperatorTok{/}\NormalTok{MISSING ANALYSIS.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/ANOVA/anovaSPSS} \caption{\label{fig:anovaSPSS}SPSS Output for One-Way Independent ANOVA}\label{fig:anovaSPSS}
\end{figure}

\hypertarget{sas}{%
\subsection{SAS}\label{sas}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{proc ANOVA data=anova;}
\NormalTok{	title One}\OperatorTok{-}\NormalTok{way ANOVA;}
\NormalTok{	class Group;}
\NormalTok{	model Score =}\StringTok{ }\NormalTok{Group;}
\NormalTok{	means Group }\OperatorTok{/}\NormalTok{hovtest welch;}
\NormalTok{	run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/ANOVA/anovaSAS} \caption{\label{fig:anovaSAS}SAS Output for One-Way Independent ANOVA}\label{fig:anovaSAS}
\end{figure}

\hypertarget{minitab}{%
\subsection{Minitab}\label{minitab}}

\begin{figure}[!h]
\includegraphics{Screenshots/ANOVA/anovaMinitab} \caption{\label{fig:anovaMinitab}Minitab Output for One-Way Independent ANOVA}\label{fig:anovaMinitab}
\end{figure}

\hypertarget{r}{%
\subsection{R}\label{r}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{## Compute the analysis of variance}
\NormalTok{results.anova <-}\StringTok{ }\KeywordTok{aov}\NormalTok{(anova.data}\OperatorTok{$}\NormalTok{Score }\OperatorTok{~}\StringTok{ }\NormalTok{anova.data}\OperatorTok{$}\NormalTok{Group, }\DataTypeTok{data =}\NormalTok{ anova.data)}
\CommentTok{## Summary of the analysis}
\KeywordTok{summary}\NormalTok{(results.anova)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  Df Sum Sq Mean Sq F value Pr(>F)
## anova.data$Group  3   22.6   7.524   0.308  0.819
## Residuals        36  878.9  24.415
\end{verbatim}

\hypertarget{remarks}{%
\subsection{Remarks}\label{remarks}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references}{%
\subsection{References}\label{references}}

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{factorial-independent-anova}{%
\section{Factorial Independent ANOVA}\label{factorial-independent-anova}}

An example from Hays (1974, pp.~491-493, 508-512):

"Just as before, the experimental game is under the control of the experimenter, so that each subject actually obtains the same score. After a fixed number of trials, during which the subject gets the preassigned score, he is asked to predict what his score will be on the next group of trials. Before he predicts, the subject is given `information' about how this score compares with some norm group. In one experimental condition he is told that his performance is above average for the norm group, in the second condition he is told that his score is average, and in the third condition he is told that his score is below average for the norm group. Once again, there are three experimental treatments in terms of `standings': `above average', `average', `below average'. {[}\ldots{]}One half of the subjects are told that they are being compared with college men, and the other half are told that they are being compared with professional athletes. Hence, there are two additional experimental treatments: `college norms', and `professional athlete norms'.

We wish to examine three null hypotheses:

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\item
  there is no effect of the standing given the subject{[}\ldots{]}
\item
  the actual norm group given the subjects has no effect {[}\ldots{]}
\item
  the norm-group-standing combination has no unique effect {[}\ldots{]}
\end{enumerate}

The \(\alpha\) level chosen for each of these three tests will be .05."

\begin{table}

\caption{\label{tab:unnamed-chunk-43}Data for Factorial Independent ANOVA}
\centering
\begin{tabular}[t]{lrrr}
\toprule
Norms & Above & Average & Below\\
\midrule
College men & 52 & 28 & 15\\
College men & 48 & 35 & 14\\
College men & 43 & 34 & 23\\
College men & 50 & 32 & 21\\
College men & 43 & 34 & 14\\
\addlinespace
College men & 44 & 27 & 20\\
College men & 46 & 31 & 21\\
College men & 46 & 27 & 16\\
College men & 43 & 29 & 20\\
College men & 49 & 25 & 14\\
\addlinespace
Professional Athlete & 38 & 43 & 23\\
Professional Athlete & 42 & 34 & 25\\
Professional Athlete & 42 & 33 & 18\\
Professional Athlete & 35 & 42 & 26\\
Professional Athlete & 33 & 41 & 18\\
\addlinespace
Professional Athlete & 38 & 37 & 26\\
Professional Athlete & 39 & 37 & 20\\
Professional Athlete & 34 & 40 & 19\\
Professional Athlete & 33 & 36 & 22\\
Professional Athlete & 34 & 35 & 17\\
\bottomrule
\end{tabular}
\end{table}

N = 60

\hypertarget{results-overview-1}{%
\subsection{Results Overview}\label{results-overview-1}}

\begin{table}

\caption{\label{tab:unnamed-chunk-44}Result Overview Independent Factorial ANOVA}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
F (Norm groups) & 0.35 & 0.3582 & 0.358 & 0.36 & 0.36 & 0.358\\
F (Standings) & 209.80 & 209.6418 & 209.642 & 209.64 & 209.64 & 209.642\\
F (Interaction) & 34.00 & 34.0075 & 34.007 & 34.01 & 34.01 & 34.007\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand-1}{%
\subsection{By Hand}\label{by-hand-1}}

Calculations by hand can be found in Hays, 1974, pp.~508-512.

Results:

\begin{table}

\caption{\label{tab:unnamed-chunk-45}Result from Hays (1974)}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
Source & SS & df & MS & F\\
\midrule
Rows (norm groups) & 4.2 & 1 & 4.20 & 0.35\\
Columns (standings) & 4994.1 & 2 & 2497.05 & 209.80\\
Interaction & 810.2 & 2 & 405.10 & 34.00\\
Error (within cells) & 643.2 & 54 & 11.90 & NA\\
\bottomrule
\end{tabular}
\end{table}

\textbf{Conclusion:} The null hypothesis cannot be rejected, for the main effect of norm groups. It can be rejected for the main effect of standings and the interaction effect.

\hypertarget{jasp-1}{%
\subsection{JASP}\label{jasp-1}}

\begin{figure}[!h]
\includegraphics{Screenshots/Factorial Independent ANOVA/FIanovaJASP} \caption{\label{fig:FIanovaJASP}JASP Output for Independent Factorial ANOVA}\label{fig:FIanovaJASP}
\end{figure}

\hypertarget{spss-1}{%
\subsection{SPSS}\label{spss-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{UNIANOVA Score BY Norms Standing}
  \OperatorTok{/}\NormalTok{METHOD=}\KeywordTok{SSTYPE}\NormalTok{(}\DecValTok{3}\NormalTok{)}
  \OperatorTok{/}\NormalTok{INTERCEPT=EXCLUDE}
  \OperatorTok{/}\NormalTok{CRITERIA=}\KeywordTok{ALPHA}\NormalTok{(}\FloatTok{0.05}\NormalTok{)}
  \OperatorTok{/}\NormalTok{DESIGN=Norms Standing Norms}\OperatorTok{*}\NormalTok{Standing.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Factorial Independent ANOVA/FIanovaSPSS} \caption{\label{fig:FIanovaSPSS}SPSS Output for Independent Factorial ANOVA}\label{fig:FIanovaSPSS}
\end{figure}

\hypertarget{sas-1}{%
\subsection{SAS}\label{sas-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{proc anova data=FIanova;}
\NormalTok{      class Norms Standing;}
\NormalTok{	  model Score =}\StringTok{ }\NormalTok{Norms Standing Norms}\OperatorTok{*}\NormalTok{Standing;}
\NormalTok{   run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Factorial Independent ANOVA/FIanovaSAS} \caption{\label{fig:FIanovaSAS}SAS Output for Independent Factorial ANOVA}\label{fig:FIanovaSAS}
\end{figure}

\hypertarget{minitab-1}{%
\subsection{Minitab}\label{minitab-1}}

\begin{figure}[!h]
\includegraphics{Screenshots/Factorial Independent ANOVA/FIanovaMinitab} \caption{\label{fig:FIanovaMinitab}Minitab Output for Independent Factorial ANOVA}\label{fig:FIanovaMinitab}
\end{figure}

\hypertarget{r-1}{%
\subsection{R}\label{r-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{FIanova.data2 <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"Datasets/FIanova.csv"}\NormalTok{, }\DataTypeTok{sep=}\StringTok{","}\NormalTok{)}
\CommentTok{## Compute the analysis of variance}
\NormalTok{results.anova <-}\StringTok{ }\KeywordTok{aov}\NormalTok{(FIanova.data2}\OperatorTok{$}\NormalTok{Score }\OperatorTok{~}\StringTok{ }\NormalTok{FIanova.data2}\OperatorTok{$}\NormalTok{Standing }\OperatorTok{*}\StringTok{ }\NormalTok{FIanova.data2}\OperatorTok{$}\NormalTok{Norms, }\DataTypeTok{data =}\NormalTok{ FIanova.data2)}
\CommentTok{## Summary of the analysis}
\KeywordTok{summary}\NormalTok{(results.anova)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                            Df Sum Sq Mean Sq F value   Pr(>F)
## FIanova.data2$Standing                      2   4994  2497.1 209.642  < 2e-16
## FIanova.data2$Norms                         1      4     4.3   0.358    0.552
## FIanova.data2$Standing:FIanova.data2$Norms  2    810   405.1  34.007 2.76e-10
## Residuals                                  54    643    11.9                 
##                                               
## FIanova.data2$Standing                     ***
## FIanova.data2$Norms                           
## FIanova.data2$Standing:FIanova.data2$Norms ***
## Residuals                                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\hypertarget{remarks-1}{%
\subsection{Remarks}\label{remarks-1}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references-1}{%
\subsection{References}\label{references-1}}

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{kruskal-wallis-anova}{%
\section{Kruskal-Wallis ANOVA}\label{kruskal-wallis-anova}}

An example from Hays (1974, pp.~782-784):

``For example, suppose that three groups of small children were given the task of learning to discriminate between pairs of stimuli. Each child was given a series of pairs of stimuli, in which each pair differed in a variety of ways. However, attached to the choice of one member of a pair was a reward, and within an experimental condition, the cue for the rewarded stimulus was always the same. On the other hand, the experimental treatments themselves differed in the relevant cue for discrimination: in treatment I, the cue was form, in treatment II, color, and in treatment III, size. Some 36 children of the same sex and age were chosen at random and assigned at random to the three groups, with 12 children per group. The dependent variable was the number of trials to a fixed criterion of learning. Suppose that the data turned out the be as shown{[}\ldots{]}''

\begin{table}

\caption{\label{tab:unnamed-chunk-49}Data for Kruskal-Wallis ANOVA}
\centering
\begin{tabular}[t]{rrr}
\toprule
Treatment.I & Treatment.II & Treatment.III\\
\midrule
6 & 31 & 13\\
11 & 7 & 32\\
12 & 9 & 31\\
20 & 11 & 30\\
24 & 16 & 28\\
\addlinespace
21 & 19 & 29\\
18 & 17 & 25\\
15 & 11 & 26\\
14 & 22 & 26\\
10 & 23 & 27\\
\addlinespace
8 & 27 & 26\\
14 & 26 & 19\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview-2}{%
\subsection{Results Overview}\label{results-overview-2}}

\begin{table}

\caption{\label{tab:unnamed-chunk-50}Result Overview Kruskal-Wallis ANOVA}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
H' & 13.85 & 13.8444 & 13.844 & 13.8444 & 13.84 & 13.844\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand-2}{%
\subsection{By Hand}\label{by-hand-2}}

Calculations by hand can be found in Hays, 1974, pp.~782-784.

Result:

H = 13.85

Significant for \(\alpha\) = .01 or less.

\hypertarget{jasp-2}{%
\subsection{JASP}\label{jasp-2}}

\begin{figure}[!h]
\includegraphics{Screenshots/Kruskal-Wallis ANOVA/kwaJASP} \caption{\label{fig:kwaJASP}JASP Output for Kruskal-Wallis ANOVA}\label{fig:kwaJASP}
\end{figure}

\hypertarget{spss-2}{%
\subsection{SPSS}\label{spss-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\OperatorTok{*}\NormalTok{Nonparametric Tests}\OperatorTok{:}\StringTok{ }\NormalTok{Independent Samples. }
\NormalTok{NPTESTS }
  \OperatorTok{/}\NormalTok{INDEPENDENT }\KeywordTok{TEST}\NormalTok{ (Score) }\KeywordTok{GROUP}\NormalTok{ (Treatment) }\KeywordTok{KRUSKAL_WALLIS}\NormalTok{(}\DataTypeTok{COMPARE=}\NormalTok{NONE) }
  \OperatorTok{/}\NormalTok{MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE}
  \OperatorTok{/}\NormalTok{CRITERIA ALPHA=}\FloatTok{0.05}\NormalTok{  CILEVEL=}\FloatTok{95.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Kruskal-Wallis ANOVA/kwaSPSS} \caption{\label{fig:kwaSPSS}SPSS Output for Kruskal-Wallis ANOVA}\label{fig:kwaSPSS}
\end{figure}

\hypertarget{sas-2}{%
\subsection{SAS}\label{sas-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC npar1way data=work.KWanova ;}
\NormalTok{class Treatment;}
\NormalTok{var Score;}
\NormalTok{run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Kruskal-Wallis ANOVA/kwaSAS} \caption{\label{fig:kwaSAS}SAS Output for Kruskal-Wallis ANOVA}\label{fig:kwaSAS}
\end{figure}

\hypertarget{minitab-2}{%
\subsection{Minitab}\label{minitab-2}}

\begin{figure}[!h]
\includegraphics{Screenshots/Kruskal-Wallis ANOVA/kwaMinitab} \caption{\label{fig:kwaMinitab}Minitab Output for Kruskal-Wallis ANOVA}\label{fig:kwaMinitab}
\end{figure}

\hypertarget{r-2}{%
\subsection{R}\label{r-2}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{kruskal.test}\NormalTok{(Score}\OperatorTok{~}\NormalTok{Treatment, }\DataTypeTok{data =}\NormalTok{ KWA.data2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 	Kruskal-Wallis rank sum test
## 
## data:  Score by Treatment
## Kruskal-Wallis chi-squared = 13.844, df = 2, p-value = 0.0009857
\end{verbatim}

\hypertarget{remarks-2}{%
\subsection{Remarks}\label{remarks-2}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references-2}{%
\subsection{References}\label{references-2}}

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{one-way-repeated-measures-anova}{%
\section{One-Way Repeated-Measures ANOVA}\label{one-way-repeated-measures-anova}}

An example from Kerlinger (1969, pp.~242-248):

``A principal of a school and the members of his staff decided to introduce a program of education in intergroup relations as an addition to the school's curriculum. One of the problems that arose was in the use of motion pictures. Films were shown in the initial phases of the program, but the results were not too encouraging. {[}\ldots\} They decided to test the hypothesis that seeing the films and then discussing them would improve the viewers' attitudes toward minority group members more than would just seeing the films. For a preliminary study the staff randomly selected a group of students from the total student body and attempted to pair the students on intelligence and socioeconomic background until ten pairs were obtained {[}\ldots{]} Each member of each pair was randomly assigned to either an experimental or a control group, and then both groups were shown a new film on intergroup relations. The A1 (experimental) group had a discission session after the picture was shown; the A2 (control) group had no such discussion afrer the film. Both groups were tested with a scale designed to measures attitudes toward minority groups.''

\begin{table}

\caption{\label{tab:unnamed-chunk-55}Data for One-Way Repeated-Measures ANOVA}
\centering
\begin{tabular}[t]{rr}
\toprule
A1.experimental. & A2.control.\\
\midrule
8 & 6\\
9 & 8\\
5 & 3\\
4 & 2\\
2 & 1\\
\addlinespace
10 & 7\\
3 & 1\\
12 & 7\\
6 & 6\\
11 & 9\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview-3}{%
\subsection{Results Overview}\label{results-overview-3}}

\begin{table}

\caption{\label{tab:unnamed-chunk-56}Result Overview One-Way Repeated-Measures ANOVA}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
F & 22.47 & 22.5 & 22.5 & 22.5 & 22.5 & 22.5\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand-3}{%
\subsection{By Hand}\label{by-hand-3}}

Calculations by hand can be found in Kerlinger, 1969, pp.~242-248.

Results:

\begin{table}

\caption{\label{tab:unnamed-chunk-57}Result from Kerlinger (1969)}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
Source & df & SS & MS & F\\
\midrule
Within groups & 1 & 20 & 20.00 & 22.47\\
Between groups & 9 & 182 & 20.22 & 22.72\\
Residual & 9 & 8 & 0.89 & NA\\
Totals & 19 & 210 & NA & NA\\
\bottomrule
\end{tabular}
\end{table}

\textbf{Conclusion:} All F-values are significant for \(\alpha\) = .001 or less.

\hypertarget{jasp-3}{%
\subsection{JASP}\label{jasp-3}}

\begin{figure}[!h]
\includegraphics{Screenshots/Repeated Measures ANOVA/ranovaJASP} \caption{\label{fig:ranovaJASP}JASP Output for One-Way Repeated-Measures ANOVA}\label{fig:ranovaJASP}
\end{figure}

\hypertarget{spss-3}{%
\subsection{SPSS}\label{spss-3}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet2.}
\NormalTok{GLM A1.experimental A2.control}
  \OperatorTok{/}\NormalTok{WSFACTOR=Condition }\DecValTok{2}\NormalTok{ Polynomial }
  \OperatorTok{/}\NormalTok{METHOD=}\KeywordTok{SSTYPE}\NormalTok{(}\DecValTok{3}\NormalTok{)}
  \OperatorTok{/}\NormalTok{CRITERIA=}\KeywordTok{ALPHA}\NormalTok{(.}\DecValTok{05}\NormalTok{)}
  \OperatorTok{/}\NormalTok{WSDESIGN=Condition.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Repeated Measures ANOVA/ranovaSPSS} \caption{\label{fig:ranovaSPSS}SPSS Output for One-Way Repeated-Measures ANOVA}\label{fig:ranovaSPSS}
\end{figure}

\hypertarget{sas-3}{%
\subsection{SAS}\label{sas-3}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC GLM DATA=work.ranova;}
\NormalTok{  CLASS Subject Condition;}
\NormalTok{  MODEL Score =}\StringTok{ }\NormalTok{Subject Condition;}
\NormalTok{RUN; }
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Repeated Measures ANOVA/ranovaSAS} \caption{\label{fig:ranovaSAS}SAS Output for One-Way Repeated-Measures ANOVA}\label{fig:ranovaSAS}
\end{figure}

\hypertarget{minitab-3}{%
\subsection{Minitab}\label{minitab-3}}

\begin{figure}[!h]
\includegraphics{Screenshots/Repeated Measures ANOVA/ranovaMinitab} \caption{\label{fig:ranovaMinitab}Minitab Output for One-Way Repeated-Measures ANOVA}\label{fig:ranovaMinitab}
\end{figure}

\hypertarget{r-3}{%
\subsection{R}\label{r-3}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(}\KeywordTok{aov}\NormalTok{(Score }\OperatorTok{~}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(ranova.data2}\OperatorTok{$}\NormalTok{Condition) }\OperatorTok{+}\StringTok{ }\KeywordTok{Error}\NormalTok{(}\KeywordTok{as.factor}\NormalTok{(ranova.data2}\OperatorTok{$}\NormalTok{Subject)}\OperatorTok{/}\KeywordTok{as.factor}\NormalTok{(ranova.data2}\OperatorTok{$}\NormalTok{Condition)), }\DataTypeTok{data=}\NormalTok{ranova.data2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Error: as.factor(ranova.data2$Subject)
##           Df Sum Sq Mean Sq F value Pr(>F)
## Residuals  9    182   20.22               
## 
## Error: as.factor(ranova.data2$Subject):as.factor(ranova.data2$Condition)
##                                   Df Sum Sq Mean Sq F value  Pr(>F)   
## as.factor(ranova.data2$Condition)  1     20  20.000    22.5 0.00105 **
## Residuals                          9      8   0.889                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\hypertarget{remarks-3}{%
\subsection{Remarks}\label{remarks-3}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references-3}{%
\subsection{References}\label{references-3}}

Kerlinger, F. N. (1969). \emph{Foundations of behavioral research}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{friedman-test}{%
\section{Friedman Test}\label{friedman-test}}

An example from Hays (1974, pp.~785-786):

``For example, in an experiment with four experimental treatments (J = 4), 11 groups of 4 matched subjects apiece were used. Within each matched group the four subjects were assigned at random to the four treatments, on subject per treatment.''

\begin{table}

\caption{\label{tab:unnamed-chunk-62}Data for Friedman Test}
\centering
\begin{tabular}[t]{rrrrr}
\toprule
Groups & Treatment.I & Treatment.II & Treatment.III & Treatment.IV\\
\midrule
1 & 1 & 4 & 8 & 0\\
2 & 2 & 3 & 13 & 1\\
3 & 10 & 0 & 11 & 3\\
4 & 12 & 11 & 13 & 10\\
5 & 1 & 3 & 10 & 0\\
\addlinespace
6 & 10 & 3 & 11 & 9\\
7 & 4 & 12 & 10 & 11\\
8 & 10 & 4 & 5 & 3\\
9 & 10 & 4 & 9 & 3\\
10 & 14 & 4 & 7 & 2\\
\addlinespace
11 & 3 & 2 & 4 & 13\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview-4}{%
\subsection{Results Overview}\label{results-overview-4}}

\begin{table}

\caption{\label{tab:unnamed-chunk-63}Result Overview Friedman Test}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
\$\textbackslash{}chi\textasciicircum{}2\$ & 11.79 & 11.9455 & 11.945 & NA & 11.95 & 11.945\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand-4}{%
\subsection{By Hand}\label{by-hand-4}}

Calculations by hand can be found in Hays, 1974, pp.~785-786.

Result:

\(\chi^2\) = 11.79

Significant for \(\alpha\) = .01 or less.

\hypertarget{jasp-4}{%
\subsection{JASP}\label{jasp-4}}

\begin{figure}[!h]
\includegraphics{Screenshots/Friedman Test/FriedmanJASP} \caption{\label{fig:FriedmanJASP}JASP Output for Friedman Test}\label{fig:FriedmanJASP}
\end{figure}

\hypertarget{spss-4}{%
\subsection{SPSS}\label{spss-4}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\OperatorTok{*}\NormalTok{Nonparametric Tests}\OperatorTok{:}\StringTok{ }\NormalTok{Related Samples. }
\NormalTok{NPTESTS }
  \OperatorTok{/}\NormalTok{RELATED }\KeywordTok{TEST}\NormalTok{(Treatment.I Treatment.II Treatment.III Treatment.IV) }\KeywordTok{FRIEDMAN}\NormalTok{(}\DataTypeTok{COMPARE=}\NormalTok{NONE) }
  \OperatorTok{/}\NormalTok{MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE}
  \OperatorTok{/}\NormalTok{CRITERIA ALPHA=}\FloatTok{0.05}\NormalTok{  CILEVEL=}\FloatTok{95.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Friedman Test/FriedmanSPSS} \caption{\label{fig:FriedmanSPSS}SPSS Output for Friedman Test}\label{fig:FriedmanSPSS}
\end{figure}

\hypertarget{sas-4}{%
\subsection{SAS}\label{sas-4}}

Not available in SAS.

\hypertarget{minitab-4}{%
\subsection{Minitab}\label{minitab-4}}

\begin{figure}[!h]
\includegraphics{Screenshots/Friedman Test/FriedmanMinitab} \caption{\label{fig:FriedmanMinitab}Minitab Output for Friedman Test}\label{fig:FriedmanMinitab}
\end{figure}

\hypertarget{r-4}{%
\subsection{R}\label{r-4}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{friedman.test}\NormalTok{(Friedman.data2}\OperatorTok{$}\NormalTok{Score, }\DataTypeTok{groups =}\NormalTok{ Friedman.data2}\OperatorTok{$}\NormalTok{Treatment, }\DataTypeTok{blocks =}\NormalTok{ Friedman.data2}\OperatorTok{$}\NormalTok{Groups)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 	Friedman rank sum test
## 
## data:  Friedman.data2$Score, Friedman.data2$Treatment and Friedman.data2$Groups
## Friedman chi-squared = 11.945, df = 3, p-value = 0.007572
\end{verbatim}

\hypertarget{remarks-4}{%
\subsection{Remarks}\label{remarks-4}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references-4}{%
\subsection{References}\label{references-4}}

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{ancova}{%
\section{ANCOVA}\label{ancova}}

An example from Field (2018 pp.~522-523, 576-577):

``Imagine we wanted to contribute to this literature by running a study in which we randomized people into three groups: (1) a control group {[}\ldots{]}; (2) 15 minutes of puppy therapy (a low-dose group); and (3) 30 minutes of puppy contact (a high-dose group). The dependent variable was a measure of happiness ranging from 0 (as unhappy as I can possibly imagine being) to 10 (as happy as I can possibly imagine being). {[}\ldots{]} The researchers {[}\ldots{]} suddenly realized that a participant's love of dogs would affect whether puppy therapy would affect happiness. Therefore, they repeated the study on different participants, but included a self-report measure of love of puppies from 0 {[}\ldots{]} to 7.''

\begin{table}

\caption{\label{tab:unnamed-chunk-67}Data for ANCOVA}
\centering
\begin{tabular}[t]{rrrr}
\toprule
Person & Dose & Happiness & Puppy\_love\\
\midrule
1 & 1 & 3 & 4\\
2 & 1 & 2 & 1\\
3 & 1 & 5 & 5\\
4 & 1 & 2 & 1\\
5 & 1 & 2 & 2\\
\addlinespace
6 & 1 & 2 & 2\\
7 & 1 & 7 & 7\\
8 & 1 & 2 & 4\\
9 & 1 & 4 & 5\\
10 & 2 & 7 & 5\\
\addlinespace
11 & 2 & 5 & 3\\
12 & 2 & 3 & 1\\
13 & 2 & 4 & 2\\
14 & 2 & 4 & 2\\
15 & 2 & 7 & 6\\
\addlinespace
16 & 2 & 5 & 4\\
17 & 2 & 4 & 2\\
18 & 3 & 9 & 1\\
19 & 3 & 2 & 3\\
20 & 3 & 6 & 5\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview-5}{%
\subsection{Results Overview}\label{results-overview-5}}

\begin{table}

\caption{\label{tab:unnamed-chunk-68}Result Overview ANCOVA}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
  & JASP & SPSS & SAS & Minitab & R\\
\midrule
F (Dose) & 4.1419 & 4.142 & 4.14 & 4.14 & 4.1419\\
F (Puppy\_love) & 4.9587 & 4.959 & 4.96 & 4.96 & 4.9587\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{jasp-5}{%
\subsection{JASP}\label{jasp-5}}

\begin{figure}[!h]
\includegraphics{Screenshots/ANCOVA/ancovaJASP} \caption{\label{fig:ancovaJASP}JASP Output for ANCOVA}\label{fig:ancovaJASP}
\end{figure}

\hypertarget{spss-5}{%
\subsection{SPSS}\label{spss-5}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{UNIANOVA Happiness BY Dose WITH Puppy_love}
  \OperatorTok{/}\KeywordTok{CONTRAST}\NormalTok{(Dose)=Simple}
  \OperatorTok{/}\NormalTok{METHOD=}\KeywordTok{SSTYPE}\NormalTok{(}\DecValTok{3}\NormalTok{)}
  \OperatorTok{/}\NormalTok{INTERCEPT=INCLUDE}
  \OperatorTok{/}\NormalTok{PRINT ETASQ}
  \OperatorTok{/}\NormalTok{CRITERIA=}\KeywordTok{ALPHA}\NormalTok{(.}\DecValTok{05}\NormalTok{)}
  \OperatorTok{/}\NormalTok{DESIGN=Puppy_love Dose.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/ANCOVA/ancovaSPSS} \caption{\label{fig:ancovaSPSS}SPSS Output for ANCOVA}\label{fig:ancovaSPSS}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/ANCOVA/contrastsSPSS} \caption{\label{fig:ancovaSPSS2}SPSS Output for ANCOVA Contrasts}\label{fig:ancovaSPSS2}
\end{figure}

\hypertarget{sas-5}{%
\subsection{SAS}\label{sas-5}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC GLM data=work.ANCOVA;}
\NormalTok{CLASS Dose;}
\NormalTok{MODEL Happiness =}\StringTok{ }\NormalTok{Dose Puppy_love }\OperatorTok{/}\StringTok{ }\NormalTok{SOLUTION ss3;}
\NormalTok{LSMEANS Dose }\OperatorTok{/}\StringTok{ }\NormalTok{STDERR PDIFF CL ADJUST =}\StringTok{ }\NormalTok{BON;}
\NormalTok{OUTPUT OUT =}\StringTok{ }\NormalTok{pred p=ybar r=resid;}
\NormalTok{RUN;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/ANCOVA/ancovaSAS} \caption{\label{fig:ancovaSAS}SAS Output for ANCOVA}\label{fig:ancovaSAS}
\end{figure}

\hypertarget{minitab-5}{%
\subsection{Minitab}\label{minitab-5}}

\begin{figure}[!h]
\includegraphics{Screenshots/ANCOVA/ancovaMinitab} \caption{\label{fig:ancovaMinitab}Minitab Output for ANCOVA}\label{fig:ancovaMinitab}
\end{figure}

\hypertarget{r-5}{%
\subsection{R}\label{r-5}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{## install.packages("car")}
\KeywordTok{library}\NormalTok{(}\StringTok{"car"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: carData
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit <-}\StringTok{ }\KeywordTok{aov}\NormalTok{(Happiness}\OperatorTok{~}\KeywordTok{as.factor}\NormalTok{(Dose) }\OperatorTok{+}\StringTok{ }\NormalTok{Puppy_love, }\DataTypeTok{data =}\NormalTok{ ANCOVA.data)}
\KeywordTok{Anova}\NormalTok{(fit, }\DataTypeTok{type =} \StringTok{"III"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Anova Table (Type III tests)
## 
## Response: Happiness
##                 Sum Sq Df F value  Pr(>F)  
## (Intercept)     12.943  1  4.2572 0.04920 *
## as.factor(Dose) 25.185  2  4.1419 0.02745 *
## Puppy_love      15.076  1  4.9587 0.03483 *
## Residuals       79.047 26                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\hypertarget{remarks-5}{%
\subsection{Remarks}\label{remarks-5}}

All differences in results between the software are due to rounding.

\hypertarget{references-5}{%
\subsection{References}\label{references-5}}

Field, A. (2018). \emph{Discovering statistics using IBM SPSS statistics}. Los Angeles, CA: SAGE.

\hypertarget{manova}{%
\section{MANOVA}\label{manova}}

An example from Field (2018 pp.~738-739):

``Most psychopathologies have both behavioural and cognitive elements to them. For example, for someone with OCD who has an obsession with germs and contamination, the disorder might manifest itself in the number of times they both wash their hands (behavior) and \emph{think about} washing their hands (cognition). To gauge the success of therapy, it is not enough to look only at behavioural outcomes (such as whether obsessive behaviours are reduced); we need to look at whether cognitions are changed too. Hence, the clinical psychologist measured two outcomes: the occurrence of obsession-related behaviours (Actions) and the occurrence of obsession-related cognitions (Thoughts) on a single day.''

\begin{table}

\caption{\label{tab:unnamed-chunk-73}Data for MANOVA}
\centering
\begin{tabular}[t]{rrr}
\toprule
Group & Actions & Thoughts\\
\midrule
1 & 5 & 14\\
1 & 5 & 11\\
1 & 4 & 16\\
1 & 4 & 13\\
1 & 5 & 12\\
\addlinespace
1 & 3 & 14\\
1 & 7 & 12\\
1 & 6 & 15\\
1 & 6 & 16\\
1 & 4 & 11\\
\addlinespace
2 & 4 & 14\\
2 & 4 & 15\\
2 & 1 & 13\\
2 & 1 & 14\\
2 & 4 & 15\\
\addlinespace
2 & 6 & 19\\
2 & 5 & 13\\
2 & 5 & 18\\
2 & 2 & 14\\
2 & 5 & 17\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview-6}{%
\subsection{Results Overview}\label{results-overview-6}}

\begin{table}

\caption{\label{tab:unnamed-chunk-74}Result Overview MANOVA}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
  & JASP & SPSS & SAS & Minitab & R\\
\midrule
F (Multivariate Pillai) & 2.5567 & 2.557 & 2.56 & 2.557 & 2.5567\\
F (Univariate Actions) & 2.7706 & 2.771 & 2.77 & 2.770 & 2.7706\\
F (Univariate Thoughts) & 2.1541 & 2.154 & 2.15 & 2.150 & 2.1541\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{jasp-6}{%
\subsection{JASP}\label{jasp-6}}

\begin{figure}[!h]
\includegraphics{Screenshots/MANOVA/MANOVAjasp} \caption{\label{fig:manovaJASP}JASP Output for MANOVA}\label{fig:manovaJASP}
\end{figure}

\hypertarget{spss-6}{%
\subsection{SPSS}\label{spss-6}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet2.}
\NormalTok{GLM Actions Thoughts BY Group}
  \OperatorTok{/}\NormalTok{METHOD=}\KeywordTok{SSTYPE}\NormalTok{(}\DecValTok{3}\NormalTok{)}
  \OperatorTok{/}\NormalTok{INTERCEPT=INCLUDE}
  \OperatorTok{/}\NormalTok{CRITERIA=}\KeywordTok{ALPHA}\NormalTok{(.}\DecValTok{05}\NormalTok{)}
  \OperatorTok{/}\NormalTok{DESIGN=}\StringTok{ }\NormalTok{Group.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/MANOVA/MANOVAspss} \caption{\label{fig:manovaSPSS}SPSS Output for MANOVA}\label{fig:manovaSPSS}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/MANOVA/ANOVASspss} \caption{\label{fig:manovaSPSS2}SPSS Output for MANOVA}\label{fig:manovaSPSS2}
\end{figure}

\hypertarget{sas-6}{%
\subsection{SAS}\label{sas-6}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{proc glm data=}\StringTok{ }\NormalTok{work.MANOVA plots=none;}
\NormalTok{  class Group;}
\NormalTok{  model Actions Thoughts =}\StringTok{ }\NormalTok{group }\OperatorTok{/}\StringTok{ }\NormalTok{ss3;}
\NormalTok{  manova h=Group;}
\NormalTok{run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/MANOVA/MANOVAsas} \caption{\label{fig:manovaSAS}SAS Output for MANOVA}\label{fig:manovaSAS}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/MANOVA/ANOVASsas} \caption{\label{fig:manovaSAS2}SAS Output for MANOVA}\label{fig:manovaSAS2}
\end{figure}

\hypertarget{minitab-6}{%
\subsection{Minitab}\label{minitab-6}}

\begin{figure}[!h]
\includegraphics{Screenshots/MANOVA/MANOVAminitab} \caption{\label{fig:manovaMinitab}Minitab Output for MANOVA}\label{fig:manovaMinitab}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/MANOVA/ANOVASminitab} \caption{\label{fig:manovaMinitab2}Minitab Output for MANOVA}\label{fig:manovaMinitab2}
\end{figure}

\hypertarget{r-6}{%
\subsection{R}\label{r-6}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DVmanova <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(MANOVA.data}\OperatorTok{$}\NormalTok{Thoughts, MANOVA.data}\OperatorTok{$}\NormalTok{Actions)}
\NormalTok{fit <-}\StringTok{ }\KeywordTok{manova}\NormalTok{(DVmanova }\OperatorTok{~}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(Group), }\DataTypeTok{data =}\NormalTok{ MANOVA.data)}
\KeywordTok{summary}\NormalTok{(fit, }\DataTypeTok{test =}\StringTok{"Pillai"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  Df  Pillai approx F num Df den Df  Pr(>F)  
## as.factor(Group)  2 0.31845   2.5567      4     54 0.04904 *
## Residuals        27                                         
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(fit, }\DataTypeTok{test =}\StringTok{"Wilks"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  Df   Wilks approx F num Df den Df  Pr(>F)  
## as.factor(Group)  2 0.69851   2.5545      4     52 0.04966 *
## Residuals        27                                         
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(fit, }\DataTypeTok{test =}\StringTok{"Hotelling-Lawley"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  Df Hotelling-Lawley approx F num Df den Df Pr(>F)  
## as.factor(Group)  2          0.40734   2.5459      4     50 0.0508 .
## Residuals        27                                                 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(fit, }\DataTypeTok{test =}\StringTok{"Roy"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  Df    Roy approx F num Df den Df  Pr(>F)  
## as.factor(Group)  2 0.3348   4.5198      2     27 0.02027 *
## Residuals        27                                        
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary.aov}\NormalTok{(fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Response 1 :
##                  Df  Sum Sq Mean Sq F value Pr(>F)
## as.factor(Group)  2  19.467  9.7333  2.1541 0.1355
## Residuals        27 122.000  4.5185               
## 
##  Response 2 :
##                  Df Sum Sq Mean Sq F value  Pr(>F)  
## as.factor(Group)  2 10.467  5.2333  2.7706 0.08046 .
## Residuals        27 51.000  1.8889                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\hypertarget{remarks-6}{%
\subsection{Remarks}\label{remarks-6}}

All differences in results between the software are due to rounding.

\hypertarget{references-6}{%
\subsection{References}\label{references-6}}

Field, A. (2018). \emph{Discovering statistics using IBM SPSS statistics}. Los Angeles, CA: SAGE.

\hypertarget{mixed-models}{%
\chapter{Mixed Models}\label{mixed-models}}

\hypertarget{linear-mixed-models}{%
\section{Linear Mixed Models}\label{linear-mixed-models}}

The example is based on data from an Experiment performed by Freeman, Heathcote, Chalmers, and Hockley (2010). In the example a simplified analysis of the data is performed, using only Task and Stimulus as fixed factors and stimulus by subject as random effect.

\hypertarget{results-overview}{%
\subsection{Results Overview}\label{results-overview}}

\begin{table}

\caption{\label{tab:unnamed-chunk-79}Result Overview Linear Mixed Model}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
  & JASP & SPSS & SAS & Minitab & R\\
\midrule
F(Task) & 15.0731 & 15.075 & 15.07 & 15.08 & 15.07\\
F(Stimulus) & 88.7032 & 88.716 & 88.70 & 88.72 & 88.70\\
F(Task X Stimulus) & 37.8429 & 37.846 & 37.84 & 37.85 & 37.84\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{jasp}{%
\subsection{JASP}\label{jasp}}

\begin{figure}[!h]
\includegraphics{Screenshots/Linear Mixed Model/lmmJASP} \caption{\label{fig:lmmJASP}JASP Output for Linear Mixed Model}\label{fig:lmmJASP}
\end{figure}

\hypertarget{spss}{%
\subsection{SPSS}\label{spss}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{MIXED rt BY task stimulus WITH NumID}
  \OperatorTok{/}\NormalTok{CRITERIA=}\KeywordTok{DFMETHOD}\NormalTok{(SATTERTHWAITE) }\KeywordTok{CIN}\NormalTok{(}\DecValTok{95}\NormalTok{) }\KeywordTok{MXITER}\NormalTok{(}\DecValTok{100}\NormalTok{) }\KeywordTok{MXSTEP}\NormalTok{(}\DecValTok{10}\NormalTok{) }\KeywordTok{SCORING}\NormalTok{(}\DecValTok{1}\NormalTok{) }
    \KeywordTok{SINGULAR}\NormalTok{(}\FloatTok{0.000000000001}\NormalTok{) }\KeywordTok{HCONVERGE}\NormalTok{(}\DecValTok{0}\NormalTok{, ABSOLUTE) }\KeywordTok{LCONVERGE}\NormalTok{(}\DecValTok{0}\NormalTok{, ABSOLUTE) }\KeywordTok{PCONVERGE}\NormalTok{(}\FloatTok{0.000001}\NormalTok{, ABSOLUTE)    }
  \OperatorTok{/}\NormalTok{FIXED=task stimulus task}\OperatorTok{*}\NormalTok{stimulus }\OperatorTok{|}\StringTok{ }\NormalTok{NOINT }\KeywordTok{SSTYPE}\NormalTok{(}\DecValTok{3}\NormalTok{)}
  \OperatorTok{/}\NormalTok{METHOD=REML}
  \OperatorTok{/}\NormalTok{RANDOM=INTERCEPT stimulus }\OperatorTok{|}\StringTok{ }\KeywordTok{SUBJECT}\NormalTok{(NumID) }\KeywordTok{COVTYPE}\NormalTok{(VC).}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Linear Mixed Model/lmmSPSS} \caption{\label{fig:lmmSPSS}SPSS Output for Linear Mixed Model}\label{fig:lmmSPSS}
\end{figure}

\hypertarget{sas}{%
\subsection{SAS}\label{sas}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{proc mixed;}
\NormalTok{class Task Stimulus;}
\NormalTok{model rt =}\StringTok{ }\NormalTok{Task Stimulus Task}\OperatorTok{*}\NormalTok{Stimulus }\OperatorTok{/}\StringTok{ }\NormalTok{ddfm=satterth;}
\NormalTok{random intercept Stimulus }\OperatorTok{/}\StringTok{ }\NormalTok{type=un subject=NumID g;}
\NormalTok{run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Linear Mixed Model/lmmSAS} \caption{\label{fig:lmmSAS}SAS Output for Linear Mixed Model}\label{fig:lmmSAS}
\end{figure}

\hypertarget{minitab}{%
\subsection{Minitab}\label{minitab}}

\begin{figure}[!h]
\includegraphics{Screenshots/Linear Mixed Model/lmmMinitab} \caption{\label{fig:lmmMinitab}Minitab Output for Linear Mixed Model}\label{fig:lmmMinitab}
\end{figure}

\hypertarget{r}{%
\subsection{R}\label{r}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#install.packages("afex")}
\KeywordTok{library}\NormalTok{(}\StringTok{"afex"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: lme4
\end{verbatim}

\begin{verbatim}
## Loading required package: Matrix
\end{verbatim}

\begin{verbatim}
## Registered S3 methods overwritten by 'lme4':
##   method                          from
##   cooks.distance.influence.merMod car 
##   influence.merMod                car 
##   dfbeta.influence.merMod         car 
##   dfbetas.influence.merMod        car
\end{verbatim}

\begin{verbatim}
## ************
## Welcome to afex. For support visit: http://afex.singmann.science/
\end{verbatim}

\begin{verbatim}
## - Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
## - Methods for calculating p-values with mixed(): 'KR', 'S', 'LRT', and 'PB'
## - 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
## - NEWS: library('emmeans') now needs to be called explicitly!
## - Get and set global package options with: afex_options()
## - Set orthogonal sum-to-zero contrasts globally: set_sum_contrasts()
## - For example analyses see: browseVignettes("afex")
## ************
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'afex'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:lme4':
## 
##     lmer
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set_sum_contrasts}\NormalTok{() }\CommentTok{## not strictly necessary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## setting contr.sum globally: options(contrasts=c('contr.sum', 'contr.poly'))
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{### but always a good idea}
\NormalTok{m1 <-}\StringTok{ }\KeywordTok{mixed}\NormalTok{(rt }\OperatorTok{~}\StringTok{ }\NormalTok{task}\OperatorTok{*}\NormalTok{stimulus }\OperatorTok{+}
\StringTok{              }\NormalTok{(stimulus}\OperatorTok{|}\NormalTok{id), }\DataTypeTok{data =}\NormalTok{ LMM.data, }\DataTypeTok{method=}\StringTok{"S"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Fitting one lmer() model. [DONE]
## Calculating p-values. [DONE]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Mixed Model Anova Table (Type 3 tests, S-method)
## 
## Model: rt ~ task * stimulus + (stimulus | id)
## Data: LMM.data
##          Effect       df         F p.value
## 1          task 1, 42.98 15.07 ***   <.001
## 2      stimulus 1, 42.89 88.70 ***   <.001
## 3 task:stimulus 1, 42.89 37.84 ***   <.001
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1
\end{verbatim}

\hypertarget{remarks}{%
\subsection{Remarks}\label{remarks}}

All differences in results between the software are due to rounding.

\hypertarget{references}{%
\subsection{References}\label{references}}

Freeman, E., Heathcote, A., Chalmers, K., \& Hockley, W. (2010). Item effects in recognition memory for words. \emph{Journal of Memory and Language, 62}(1), 1-18.

\hypertarget{regression}{%
\chapter{Regression}\label{regression}}

\hypertarget{correlation}{%
\section{Correlation}\label{correlation}}

An example from Hays (1974, pp.~633-635):

``The teacher collected data for a class of 91 students, obtaining for each a score \emph{X}, based on the number of courses in high-school mathematics, and a score \emph{Y}, the actual score on the final examination for the course.''

\begin{table}

\caption{\label{tab:unnamed-chunk-84}Data for Correlation}
\centering
\begin{tabular}[t]{rr}
\toprule
X & Y\\
\midrule
2.0 & 22\\
2.0 & 17\\
2.0 & 16\\
2.0 & 14\\
2.0 & 10\\
\addlinespace
2.0 & 9\\
2.0 & 7\\
2.0 & 5\\
2.0 & 3\\
2.0 & 2\\
\addlinespace
2.5 & 26\\
2.5 & 23\\
2.5 & 18\\
2.5 & 18\\
2.5 & 16\\
\addlinespace
2.5 & 13\\
2.5 & 12\\
2.5 & 10\\
2.5 & 10\\
2.5 & 7\\
\addlinespace
2.5 & 6\\
3.0 & 29\\
3.0 & 26\\
3.0 & 26\\
3.0 & 24\\
\addlinespace
3.0 & 24\\
3.0 & 23\\
3.0 & 22\\
3.0 & 16\\
3.0 & 9\\
\addlinespace
3.0 & 8\\
3.5 & 34\\
3.5 & 26\\
3.5 & 25\\
3.5 & 23\\
\addlinespace
3.5 & 23\\
3.5 & 22\\
3.5 & 22\\
3.5 & 19\\
3.5 & 18\\
\addlinespace
3.5 & 17\\
3.5 & 17\\
3.5 & 17\\
3.5 & 12\\
3.5 & 8\\
\addlinespace
4.0 & 36\\
4.0 & 35\\
4.0 & 30\\
4.0 & 27\\
4.0 & 25\\
\addlinespace
4.0 & 25\\
4.0 & 24\\
4.0 & 21\\
4.0 & 20\\
4.0 & 19\\
\addlinespace
4.0 & 19\\
4.0 & 18\\
4.0 & 18\\
4.0 & 12\\
4.0 & 3\\
\addlinespace
4.5 & 28\\
4.5 & 27\\
4.5 & 16\\
5.0 & 41\\
5.0 & 32\\
\addlinespace
5.0 & 27\\
5.0 & 19\\
5.5 & 32\\
5.5 & 25\\
5.5 & 25\\
\addlinespace
6.0 & 46\\
6.0 & 38\\
6.0 & 34\\
6.0 & 33\\
6.0 & 27\\
\addlinespace
6.0 & 20\\
6.5 & 44\\
6.5 & 37\\
6.5 & 32\\
6.5 & 28\\
\addlinespace
7.0 & 52\\
7.0 & 46\\
7.0 & 37\\
7.5 & 42\\
7.5 & 41\\
\addlinespace
7.5 & 38\\
7.5 & 35\\
8.0 & 53\\
8.0 & 48\\
8.0 & 40\\
\addlinespace
8.0 & 40\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview}{%
\subsection{Results Overview}\label{results-overview}}

\begin{table}

\caption{\label{tab:unnamed-chunk-85}Result Overview Correlation}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
Pearson & 0.81 & 0.8064 & 0.806 & 0.8064 & 0.806 & 0.8064\\
Spearman & NA & 0.7730 & 0.773 & 0.7730 & 0.773 & 0.7730\\
Kendall & NA & 0.6121 & 0.612 & 0.6120 & NA & 0.6120\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand}{%
\subsection{By Hand}\label{by-hand}}

Calculations by hand can be found in Hays, 1974, pp.~633-635.

Result: r = 0.81

\textbf{Note:} Hays calculated only the Pearson correlation coefficient.

\hypertarget{jasp}{%
\subsection{JASP}\label{jasp}}

\begin{figure}[!h]
\includegraphics{Screenshots/Correlation/corrJASP} \caption{\label{fig:corrJASP}JASP Output for Correlation}\label{fig:corrJASP}
\end{figure}

\hypertarget{spss}{%
\subsection{SPSS}\label{spss}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{CORRELATIONS}
  \OperatorTok{/}\NormalTok{VARIABLES=Y X}
  \OperatorTok{/}\NormalTok{PRINT=TWOTAIL NOSIG}
  \OperatorTok{/}\NormalTok{MISSING=PAIRWISE.}
\NormalTok{NONPAR CORR}
  \OperatorTok{/}\NormalTok{VARIABLES=Y X}
  \OperatorTok{/}\NormalTok{PRINT=BOTH TWOTAIL NOSIG}
  \OperatorTok{/}\NormalTok{MISSING=PAIRWISE.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Correlation/corrSPSS} \caption{\label{fig:corrSPSS}SPSS Output for Correlation}\label{fig:corrSPSS}
\end{figure}

\hypertarget{sas}{%
\subsection{SAS}\label{sas}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC CORR DATA=Correlation pearson spearman kendall;}
\NormalTok{    VAR X;}
\NormalTok{    WITH Y;}
\NormalTok{RUN;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Correlation/corrSAS} \caption{\label{fig:corrSAS}SAS Output for Correlation}\label{fig:corrSAS}
\end{figure}

\hypertarget{minitab}{%
\subsection{Minitab}\label{minitab}}

\begin{figure}[!h]
\includegraphics{Screenshots/Correlation/corrMinitab} \caption{\label{fig:corrMinitab}Minitab Output for Pearson Correlation}\label{fig:corrMinitab}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Correlation/corrMinitab2} \caption{\label{fig:corrMinitab2}Minitab Output for Spearman Correlation}\label{fig:corrMinitab2}
\end{figure}

\hypertarget{r}{%
\subsection{R}\label{r}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(corr.data}\OperatorTok{$}\NormalTok{X, corr.data}\OperatorTok{$}\NormalTok{Y, }\DataTypeTok{method =}\StringTok{"pearson"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 	Pearson's product-moment correlation
## 
## data:  corr.data$X and corr.data$Y
## t = 12.866, df = 89, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.7200843 0.8681910
## sample estimates:
##       cor 
## 0.8064365
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(corr.data}\OperatorTok{$}\NormalTok{X, corr.data}\OperatorTok{$}\NormalTok{Y, }\DataTypeTok{method =}\StringTok{"spearman"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in cor.test.default(corr.data$X, corr.data$Y, method = "spearman"):
## Cannot compute exact p-value with ties
\end{verbatim}

\begin{verbatim}
## 
## 	Spearman's rank correlation rho
## 
## data:  corr.data$X and corr.data$Y
## S = 28502, p-value < 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.7730333
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(corr.data}\OperatorTok{$}\NormalTok{X, corr.data}\OperatorTok{$}\NormalTok{Y, }\DataTypeTok{method =}\StringTok{"kendall"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 	Kendall's rank correlation tau
## 
## data:  corr.data$X and corr.data$Y
## z = 8.1519, p-value = 3.582e-16
## alternative hypothesis: true tau is not equal to 0
## sample estimates:
##       tau 
## 0.6120845
\end{verbatim}

\hypertarget{remarks}{%
\subsection{Remarks}\label{remarks}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references}{%
\subsection{References}\label{references}}

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{linear-regression}{%
\section{Linear Regression}\label{linear-regression}}

An example from Hays (1974, pp.~633-635):

``The teacher collected data for a class of 91 students, obtaining for each a score \emph{X}, based on the number of courses in high-school mathematics, and a score \emph{Y}, the actual score on the final examination for the course.''

\begin{table}

\caption{\label{tab:unnamed-chunk-89}Data for Regression}
\centering
\begin{tabular}[t]{rr}
\toprule
X & Y\\
\midrule
2.0 & 22\\
2.0 & 17\\
2.0 & 16\\
2.0 & 14\\
2.0 & 10\\
\addlinespace
2.0 & 9\\
2.0 & 7\\
2.0 & 5\\
2.0 & 3\\
2.0 & 2\\
\addlinespace
2.5 & 26\\
2.5 & 23\\
2.5 & 18\\
2.5 & 18\\
2.5 & 16\\
\addlinespace
2.5 & 13\\
2.5 & 12\\
2.5 & 10\\
2.5 & 10\\
2.5 & 7\\
\addlinespace
2.5 & 6\\
3.0 & 29\\
3.0 & 26\\
3.0 & 26\\
3.0 & 24\\
\addlinespace
3.0 & 24\\
3.0 & 23\\
3.0 & 22\\
3.0 & 16\\
3.0 & 9\\
\addlinespace
3.0 & 8\\
3.5 & 34\\
3.5 & 26\\
3.5 & 25\\
3.5 & 23\\
\addlinespace
3.5 & 23\\
3.5 & 22\\
3.5 & 22\\
3.5 & 19\\
3.5 & 18\\
\addlinespace
3.5 & 17\\
3.5 & 17\\
3.5 & 17\\
3.5 & 12\\
3.5 & 8\\
\addlinespace
4.0 & 36\\
4.0 & 35\\
4.0 & 30\\
4.0 & 27\\
4.0 & 25\\
\addlinespace
4.0 & 25\\
4.0 & 24\\
4.0 & 21\\
4.0 & 20\\
4.0 & 19\\
\addlinespace
4.0 & 19\\
4.0 & 18\\
4.0 & 18\\
4.0 & 12\\
4.0 & 3\\
\addlinespace
4.5 & 28\\
4.5 & 27\\
4.5 & 16\\
5.0 & 41\\
5.0 & 32\\
\addlinespace
5.0 & 27\\
5.0 & 19\\
5.5 & 32\\
5.5 & 25\\
5.5 & 25\\
\addlinespace
6.0 & 46\\
6.0 & 38\\
6.0 & 34\\
6.0 & 33\\
6.0 & 27\\
\addlinespace
6.0 & 20\\
6.5 & 44\\
6.5 & 37\\
6.5 & 32\\
6.5 & 28\\
\addlinespace
7.0 & 52\\
7.0 & 46\\
7.0 & 37\\
7.5 & 42\\
7.5 & 41\\
\addlinespace
7.5 & 38\\
7.5 & 35\\
8.0 & 53\\
8.0 & 48\\
8.0 & 40\\
\addlinespace
8.0 & 40\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview-1}{%
\subsection{Results Overview}\label{results-overview-1}}

\begin{table}

\caption{\label{tab:unnamed-chunk-90}Result Overview Independent Factorial ANOVA}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
Constant & 23.84 & 23.8352 & 23.835 & 23.8352 & 23.835 & 23.8350\\
Regression Coefficient & 5.42 & 5.3993 & 5.399 & 5.3993 & 5.399 & 5.3990\\
\$\textbackslash{}overline\{x\}\$ & 4.19 & 4.1923 & 4.192 & 4.1923 & 4.192 & 4.1923\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand-1}{%
\subsection{By Hand}\label{by-hand-1}}

Calculations by hand can be found in Hays, 1974, pp.~633-635.

Results:

y' = (5.42)(x - 4.19) + 23.84

\textbf{Note:} Hays mean-centered the equation by the mean of \(\overline{x}\) = 4.19.

\hypertarget{jasp-1}{%
\subsection{JASP}\label{jasp-1}}

\begin{figure}[!h]
\includegraphics{Screenshots/Regression/RegressionJASP} \caption{\label{fig:RegressionJASP}JASP Output for Regression}\label{fig:RegressionJASP}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Regression/RegressionJASPmeans} \caption{\label{fig:RegressionJASPmeans}JASP Output for Descriptives}\label{fig:RegressionJASPmeans}
\end{figure}

\textbf{Mean-centered regression equation:}

y' = (5.3993)(x - 4.1923) + 23.8352

\hypertarget{spss-1}{%
\subsection{SPSS}\label{spss-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DESCRIPTIVES VARIABLES=X}
  \OperatorTok{/}\NormalTok{STATISTICS=MEAN.}


\NormalTok{REGRESSION}
  \OperatorTok{/}\NormalTok{DESCRIPTIVES MEAN STDDEV CORR SIG N}
  \OperatorTok{/}\NormalTok{MISSING LISTWISE}
  \OperatorTok{/}\NormalTok{STATISTICS COEFF OUTS R ANOVA}
  \OperatorTok{/}\NormalTok{CRITERIA=}\KeywordTok{PIN}\NormalTok{(.}\DecValTok{05}\NormalTok{) }\KeywordTok{POUT}\NormalTok{(.}\DecValTok{10}\NormalTok{)}
  \OperatorTok{/}\NormalTok{NOORIGIN }
  \OperatorTok{/}\NormalTok{DEPENDENT Y}
  \OperatorTok{/}\NormalTok{METHOD=ENTER MeanCenteredX.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Regression/RegressionSPSS} \caption{\label{fig:RegressionSPSS}SPSS Output for Regression}\label{fig:RegressionSPSS}
\end{figure}

\textbf{Mean-centered regression equation:}

y' = (5.399)(x - 4.192) + 23.835

\hypertarget{sas-1}{%
\subsection{SAS}\label{sas-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{proc Reg data=Regression;}
\NormalTok{title }\StringTok{"Linear regression"}\NormalTok{;}
\NormalTok{model Y =}\StringTok{ }\NormalTok{MeanCenteredX;}
\NormalTok{run;}
	
\NormalTok{PROC MEANS DATA=Regression;}
\NormalTok{  VAR X Y;}
\NormalTok{RUN;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Regression/RegressionSAS} \caption{\label{fig:RegressionSAS}SAS Output for Regression}\label{fig:RegressionSAS}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Regression/RegressionSASmeans} \caption{\label{fig:RegressionSASmeans}SAS Output for Means}\label{fig:RegressionSASmeans}
\end{figure}

\textbf{Mean-centered regression equation:}

y' = (5.3993)(x - 4.1923077) + 23.83516

\hypertarget{minitab-1}{%
\subsection{Minitab}\label{minitab-1}}

\begin{figure}[!h]
\includegraphics{Screenshots/Regression/RegressionMinitab} \caption{\label{fig:RegressionMinitab}Minitab Output for Regression}\label{fig:RegressionMinitab}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Regression/RegressionMinitabmeans} \caption{\label{fig:RegressionMinitabmeans}Minitab Output for Means}\label{fig:RegressionMinitabmeans}
\end{figure}

\textbf{Mean-centered regression equation:}

y' = (5.399)(x - 4.192) + 23.835

\hypertarget{r-1}{%
\subsection{R}\label{r-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{regress.data2 <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"Datasets/Regression.csv"}\NormalTok{, }\DataTypeTok{sep=}\StringTok{","}\NormalTok{)}
\KeywordTok{lm}\NormalTok{(}\DataTypeTok{formula =}\NormalTok{ Y }\OperatorTok{~}\StringTok{ }\NormalTok{MeanCenteredX, }\DataTypeTok{data =}\NormalTok{ regress.data2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Y ~ MeanCenteredX, data = regress.data2)
## 
## Coefficients:
##   (Intercept)  MeanCenteredX  
##        23.835          5.399
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(regress.data2}\OperatorTok{$}\NormalTok{X)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.192308
\end{verbatim}

\textbf{Mean-centered regression equation:}

y' = (5.399)(x - 4.192308) + 23.835

\hypertarget{remarks-1}{%
\subsection{Remarks}\label{remarks-1}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references-1}{%
\subsection{References}\label{references-1}}

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{logistic-regression}{%
\section{Logistic Regression}\label{logistic-regression}}

An example:

The Titanic-dataset contains original data of all passengers of the Titanic. It contains their name, their passenger class (1st - 3rd), their age, their sex, and whether or not they survived the sinking of the ship. The logistic regression model is computed to allow predictions on a passengers survival status, based on their age, sex, and passenger class.

\hypertarget{results-overview-2}{%
\subsection{Results Overview}\label{results-overview-2}}

\begin{table}

\caption{\label{tab:unnamed-chunk-94}Result Overview Coefficents Logistic Regression}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
  & JASP & SPSS & SAS & Minitab & R\\
\midrule
Constant & 3.7597 & 3.760 & 3.7596 & 3.7600 & 3.7597\\
Age & -0.0392 & -0.039 & -0.0392 & -0.0392 & -0.0392\\
2nd Class & -1.2920 & -1.292 & -1.2920 & -1.2920 & -1.2920\\
3rd Class & -2.5214 & -2.521 & -2.5214 & -2.5210 & -2.5214\\
Sex(Male) & -2.6314 & -2.631 & -2.6313 & -2.6310 & -2.6314\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:unnamed-chunk-95}Result Overview Odds-ratio Logistic Regression}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
  & JASP & SPSS & SAS & Minitab & R\\
\midrule
Constant & 42.9339 & 42.934 & NA & NA & 42.9339\\
Age & 0.9616 & 0.962 & 0.962 & 0.9616 & 0.9616\\
2nd Class & 0.2747 & 0.275 & 0.275 & 0.2747 & 0.2747\\
3rd Class & 0.0803 & 0.080 & 0.080 & 0.0803 & 0.0803\\
Sex(Male) & 0.0720 & 0.072 & 0.072 & 0.0720 & 0.0720\\
\bottomrule
\end{tabular}
\end{table}

\textbf{Note}: The reference case to which the odds ratios are refering is a female passenger in the first class with age 0.

\hypertarget{jasp-2}{%
\subsection{JASP}\label{jasp-2}}

\begin{figure}[!h]
\includegraphics{Screenshots/Logistic Regression/LogRegJASP} \caption{\label{fig:LogRegJASP}JASP Output for Logistic Regression}\label{fig:LogRegJASP}
\end{figure}

\hypertarget{spss-2}{%
\subsection{SPSS}\label{spss-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{LOGISTIC REGRESSION VARIABLES Survived}
  \OperatorTok{/}\NormalTok{METHOD=ENTER PClass Age Sex }
  \OperatorTok{/}\KeywordTok{CONTRAST}\NormalTok{ (PClass)=}\KeywordTok{Indicator}\NormalTok{(}\DecValTok{1}\NormalTok{)}
  \OperatorTok{/}\KeywordTok{CONTRAST}\NormalTok{ (Sex)=}\KeywordTok{Indicator}\NormalTok{(}\DecValTok{1}\NormalTok{)}
  \OperatorTok{/}\NormalTok{CRITERIA=}\KeywordTok{PIN}\NormalTok{(.}\DecValTok{05}\NormalTok{) }\KeywordTok{POUT}\NormalTok{(.}\DecValTok{10}\NormalTok{) }\KeywordTok{ITERATE}\NormalTok{(}\DecValTok{20}\NormalTok{) }\KeywordTok{CUT}\NormalTok{(.}\DecValTok{5}\NormalTok{).}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Logistic Regression/LogRegSPSS} \caption{\label{fig:LogRegSPSS}SPSS Output for Logistic Regression}\label{fig:LogRegSPSS}
\end{figure}

\hypertarget{sas-2}{%
\subsection{SAS}\label{sas-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{proc logistic data=work.LogReg DESC;}
\NormalTok{  class PClass Sex }\OperatorTok{/}\StringTok{ }\NormalTok{param=reference ref=first;}
\NormalTok{  model Survived =}\StringTok{ }\NormalTok{Age Sex PClass; }
\NormalTok{run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Logistic Regression/LogRegSAS} \caption{\label{fig:LogRegSAS}SAS Output for Logistic Regression}\label{fig:LogRegSAS}
\end{figure}

\hypertarget{minitab-2}{%
\subsection{Minitab}\label{minitab-2}}

\begin{figure}[!h]
\includegraphics{Screenshots/Logistic Regression/LogRegMinitab} \caption{\label{fig:LogRegMinitab}Minitab Output for Logistic Regression}\label{fig:LogRegMinitab}
\end{figure}

\hypertarget{r-2}{%
\subsection{R}\label{r-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LogRegExample <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(}\KeywordTok{factor}\NormalTok{(Survived) }\OperatorTok{~}\NormalTok{Age }\OperatorTok{+}\StringTok{ }\KeywordTok{factor}\NormalTok{(PClass) }\OperatorTok{+}\StringTok{ }\KeywordTok{factor}\NormalTok{(Sex), }\DataTypeTok{data=}\NormalTok{LogReg.data2, }\DataTypeTok{family=}\KeywordTok{binomial}\NormalTok{(}\DataTypeTok{link=}\StringTok{"logit"}\NormalTok{))}
\KeywordTok{summary}\NormalTok{(LogRegExample)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = factor(Survived) ~ Age + factor(PClass) + factor(Sex), 
##     family = binomial(link = "logit"), data = LogReg.data2)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7226  -0.7065  -0.3917   0.6495   2.5289  
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(>|z|)    
## (Intercept)      1.172856   0.253988   4.618 3.88e-06 ***
## Age             -0.039177   0.007616  -5.144 2.69e-07 ***
## factor(PClass)1  1.271127   0.160563   7.917 2.44e-15 ***
## factor(PClass)2 -0.020835   0.138004  -0.151     0.88    
## factor(Sex)1     1.315678   0.100753  13.058  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1025.57  on 755  degrees of freedom
## Residual deviance:  695.14  on 751  degrees of freedom
##   (557 observations deleted due to missingness)
## AIC: 705.14
## 
## Number of Fisher Scoring iterations: 5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coef}\NormalTok{(LogRegExample))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     (Intercept)             Age factor(PClass)1 factor(PClass)2    factor(Sex)1 
##       3.2312094       0.9615807       3.5648686       0.9793803       3.7272788
\end{verbatim}

\hypertarget{remarks-2}{%
\subsection{Remarks}\label{remarks-2}}

All differences in results between the software are due to rounding.

\hypertarget{frequencies}{%
\chapter{Frequencies}\label{frequencies}}

\hypertarget{binomial-test}{%
\section{Binomial Test}\label{binomial-test}}

\hypertarget{example}{%
\subsection{Example}\label{example}}

An example from Hays (1974, pp.~190-192):

``Think of a hypothetical study of this question: `If a human is subjected to a stimulus below his threshold of conscious awareness, can his behavior somehow still be influenced by the presence of the stimulus?' The experimental task is as follows: the subject is seated in a room in front of a square screen divided into four equal parts. He is instructed that his task is to guess in which part of the screen a small, very faint, spot of light is thrown.''

Under the null hypothesis H\textsubscript{0}, the number of correct guesses is expected to be 1/4 of the trials N. The alternative hypothesis H\textsubscript{1} is that the number of correct guesses is larger than 1/4 of the trials N.

The subject obtained 7 correct guesses T out of 10 trials N.

What is the p-value of this result under H\textsubscript{0}?

p = 0.25

N = 10

T = 7

\hypertarget{results-overview}{%
\subsection{Results Overview}\label{results-overview}}

\begin{table}

\caption{\label{tab:unnamed-chunk-100}Result Overview Binomial Test}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
P & 0.0035 & 0.0035 & 0.004 & 0.0035 & 0.004 & 0.0035\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand}{%
\subsection{By Hand}\label{by-hand}}

Calculations by hand can be found in Hays, 1974, pp.~190-192.

Result: P = 0.0035

\hypertarget{jasp}{%
\subsection{JASP}\label{jasp}}

\begin{figure}[!h]
\includegraphics{Screenshots/Binomial Test/BinomialTestJASP} \caption{\label{fig:BinomialTestJASP}JASP Output for Binomial Test}\label{fig:BinomialTestJASP}
\end{figure}

\hypertarget{spss}{%
\subsection{SPSS}\label{spss}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET NAME DataSet1 WINDOW=FRONT. }
\OperatorTok{*}\NormalTok{Nonparametric Tests}\OperatorTok{:}\StringTok{ }\NormalTok{One Sample. }
\NormalTok{NPTESTS }
  \OperatorTok{/}\NormalTok{ONESAMPLE }\KeywordTok{TEST}\NormalTok{ (Guesses) }\KeywordTok{BINOMIAL}\NormalTok{(}\DataTypeTok{TESTVALUE=}\FloatTok{0.25} \DataTypeTok{SUCCESSCATEGORICAL=}\NormalTok{FIRST }\DataTypeTok{SUCCESSCONTINUOUS=}\KeywordTok{CUTPOINT}\NormalTok{(MIDPOINT)) }
  \OperatorTok{/}\NormalTok{MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE }
  \OperatorTok{/}\NormalTok{CRITERIA ALPHA=}\FloatTok{0.05}\NormalTok{ CILEVEL=}\FloatTok{95.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Binomial Test/BinomialTestSPSS} \caption{\label{fig:BinomialTestSPSS}SPSS Output for Binomial Test}\label{fig:BinomialTestSPSS}
\end{figure}

\hypertarget{sas}{%
\subsection{SAS}\label{sas}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC Freq data=WORK.IMPORT;}
\NormalTok{	tables Guesses }\OperatorTok{/}\StringTok{ }\KeywordTok{binomial}\NormalTok{(}\DataTypeTok{p=}\NormalTok{.}\DecValTok{25} \DataTypeTok{level=}\DecValTok{2}\NormalTok{);}
\NormalTok{	exact binomial;}
\NormalTok{run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Binomial Test/BinomialTestSAS} \caption{\label{fig:BinomialTestSAS}SAS Output for Binomial Test}\label{fig:BinomialTestSAS}
\end{figure}

\hypertarget{minitab}{%
\subsection{Minitab}\label{minitab}}

\begin{figure}[!h]
\includegraphics{Screenshots/Binomial Test/BinomialTestMinitab} \caption{\label{fig:BinomialTestMinitab}Minitab Output for Binomial Test}\label{fig:BinomialTestMinitab}
\end{figure}

\hypertarget{r}{%
\subsection{R}\label{r}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{binom.test}\NormalTok{(}\DecValTok{7}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DataTypeTok{p =} \FloatTok{0.25}\NormalTok{, }\DataTypeTok{alternative =} \StringTok{"greater"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 	Exact binomial test
## 
## data:  7 and 10
## number of successes = 7, number of trials = 10, p-value = 0.003506
## alternative hypothesis: true probability of success is greater than 0.25
## 95 percent confidence interval:
##  0.3933758 1.0000000
## sample estimates:
## probability of success 
##                    0.7
\end{verbatim}

\hypertarget{remarks}{%
\subsection{Remarks}\label{remarks}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references}{%
\subsection{References}\label{references}}

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{multinomial-test-chi-square-goodness-of-fit-test}{%
\section{Multinomial Test / Chi-square Goodness of Fit Test}\label{multinomial-test-chi-square-goodness-of-fit-test}}

\hypertarget{example-1}{%
\subsection{Example}\label{example-1}}

Think of colored marbles mixed together in a box, where the following probability distribution holds:

\begin{table}

\caption{\label{tab:unnamed-chunk-104}Probability Distribution for Multinomial Test Example}
\centering
\begin{tabular}[t]{lr}
\toprule
Color & p\\
\midrule
Black & 0.4\\
Red & 0.3\\
White & 0.3\\
\bottomrule
\end{tabular}
\end{table}

Now suppose that 10 marbles were drawn at random and with replacement. The samples shows 2 black, 3 red, and 5 white.

\begin{table}

\caption{\label{tab:unnamed-chunk-105}Sample for Multinomial Test Example}
\centering
\begin{tabular}[t]{lrr}
\toprule
Color & Count & Expected\\
\midrule
Black & 2 & 4\\
Red & 3 & 3\\
White & 5 & 3\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview-1}{%
\subsection{Results Overview}\label{results-overview-1}}

\begin{table}

\caption{\label{tab:unnamed-chunk-106}Result Overview Multinomial Test}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
  & JASP & SPSS & SAS & Minitab & R\\
\midrule
\$\textbackslash{}chi \textasciicircum{}2\$ & 2.333 & 2.333 & 2.333 & 2.333 & 2.333\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{jasp-1}{%
\subsection{JASP}\label{jasp-1}}

\begin{figure}[!h]
\includegraphics{Screenshots/Multinomial Test/mntJASP} \caption{\label{fig:mntJASP}JASP Output for Multinomial Test}\label{fig:mntJASP}
\end{figure}

\hypertarget{spss-1}{%
\subsection{SPSS}\label{spss-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{NPAR TESTS}
  \OperatorTok{/}\NormalTok{CHISQUARE=Numbered}
  \OperatorTok{/}\NormalTok{EXPECTED=}\DecValTok{4} \DecValTok{3} \DecValTok{3}
  \OperatorTok{/}\NormalTok{MISSING ANALYSIS.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Multinomial Test/mntSPSS} \caption{\label{fig:mntSPSS}SPSS Output for Multinomial Test}\label{fig:mntSPSS}
\end{figure}

\hypertarget{sas-1}{%
\subsection{SAS}\label{sas-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC FREQ DATA =}\StringTok{ }\NormalTok{chisquared;}
\NormalTok{TABLES Sex}\OperatorTok{*}\NormalTok{Preference }\OperatorTok{/}\StringTok{ }\NormalTok{chisq;}
\NormalTok{run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Multinomial Test/mntSAS} \caption{\label{fig:mntSAS}SAS Output for Multinomial Test}\label{fig:mntSAS}
\end{figure}

\hypertarget{minitab-1}{%
\subsection{Minitab}\label{minitab-1}}

\begin{figure}[!h]
\includegraphics{Screenshots/Multinomial Test/mntMinitab} \caption{\label{fig:mntMinitab}Minitab Output for Multinomial Test}\label{fig:mntMinitab}
\end{figure}

\hypertarget{r-1}{%
\subsection{R}\label{r-1}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{chisq.test}\NormalTok{(MNsample}\OperatorTok{$}\NormalTok{Count, }\DataTypeTok{p =}\NormalTok{ Pdist}\OperatorTok{$}\NormalTok{p)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in chisq.test(MNsample$Count, p = Pdist$p): Chi-squared approximation
## may be incorrect
\end{verbatim}

\begin{verbatim}
## 
## 	Chi-squared test for given probabilities
## 
## data:  MNsample$Count
## X-squared = 2.3333, df = 2, p-value = 0.3114
\end{verbatim}

\hypertarget{remarks-1}{%
\subsection{Remarks}\label{remarks-1}}

All differences in results between the software are due to rounding.

\hypertarget{chi-squared-test}{%
\section{Chi-Squared-Test}\label{chi-squared-test}}

An example from Hays (1974, pp.~728-731):

``For example, suppose that a random sample of 1-- school children is drawn. Each child is classified in two ways: the first attribute is the sex of the child, with two possible categories: {[}Male, Female{]}.
The second attribute {[}\ldots{]} is the stated preference of a child for two kinds of reading materials: {[}Fiction, Nonfiction{]}. {[}\ldots{]} The data might, for example, turn out to be:''

\begin{table}

\caption{\label{tab:unnamed-chunk-110}Data for Chi-Squared-Test}
\centering
\begin{tabular}[t]{lrr}
\toprule
  & Male & Female\\
\midrule
Fiction & 19 & 32\\
Nonfiction & 29 & 20\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{results-overview-2}{%
\subsection{Results Overview}\label{results-overview-2}}

\begin{table}

\caption{\label{tab:unnamed-chunk-111}Result Overview Chi-Squared-Test}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & By Hand & JASP & SPSS & SAS & Minitab & R\\
\midrule
\$\textbackslash{}chi \textasciicircum{}2\$ & 4.83 & 4.8145 & 4.814 & 4.8145 & 4.814 & 4.8145\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{by-hand-1}{%
\subsection{By Hand}\label{by-hand-1}}

Calculations by hand can be found in Hays, 1974, pp.~728-731.

Result: \(\chi ^2\) = 4.83

Significant for \(\alpha\) = .05 or less

\hypertarget{jasp-2}{%
\subsection{JASP}\label{jasp-2}}

\begin{figure}[!h]
\includegraphics{Screenshots/Chi Squared/ChiSquaredJASP} \caption{\label{fig:cstJASP}JASP Output for Chi-Squared-Test}\label{fig:cstJASP}
\end{figure}

\hypertarget{spss-2}{%
\subsection{SPSS}\label{spss-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CROSSTABS}
  \OperatorTok{/}\NormalTok{TABLES=Sex BY Preference}
  \OperatorTok{/}\NormalTok{FORMAT=AVALUE TABLES}
  \OperatorTok{/}\NormalTok{STATISTICS=CHISQ }
  \OperatorTok{/}\NormalTok{CELLS=COUNT }
  \OperatorTok{/}\NormalTok{COUNT ROUND CELL.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Chi Squared/ChiSquaredSPSS} \caption{\label{fig:cstSPSS}SPSS Output for Chi-Squared-Test}\label{fig:cstSPSS}
\end{figure}

\hypertarget{sas-2}{%
\subsection{SAS}\label{sas-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC FREQ DATA =}\StringTok{ }\NormalTok{chisquared;}
\NormalTok{TABLES Sex}\OperatorTok{*}\NormalTok{Preference }\OperatorTok{/}\StringTok{ }\NormalTok{chisq;}
\NormalTok{run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Chi Squared/ChiSquaredSAS} \caption{\label{fig:cstSAS}SAS Output for Chi-Squared-Test}\label{fig:cstSAS}
\end{figure}

\hypertarget{minitab-2}{%
\subsection{Minitab}\label{minitab-2}}

\begin{figure}[!h]
\includegraphics{Screenshots/Chi Squared/ChiSquaredMinitab} \caption{\label{fig:cstMinitab}Minitab Output for Chi-Squared-Test}\label{fig:cstMinitab}
\end{figure}

\hypertarget{r-2}{%
\subsection{R}\label{r-2}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{chisq.test}\NormalTok{(chiSquare.data, }\DataTypeTok{correct =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 	Pearson's Chi-squared test
## 
## data:  chiSquare.data
## X-squared = 4.8145, df = 1, p-value = 0.02822
\end{verbatim}

\hypertarget{remarks-2}{%
\subsection{Remarks}\label{remarks-2}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references-1}{%
\subsection{References}\label{references-1}}

Hays, W. L. (1974). \emph{Statistics for the social sciences (2nd Ed.)}. New York, US: Holt, Rinehart and Winston, Inc.

\hypertarget{factor}{%
\chapter{Factor}\label{factor}}

\hypertarget{principal-component-analysis}{%
\section{Principal Component Analysis}\label{principal-component-analysis}}

An example from Field (2018 pp.~795-796):

``I have noticed that a lot of students become very stressed about SPSS Statistics. Imagine that I wanted to design a questionnaire to measure a trait that I termed `SPSS anxiety'. I devised a questionnaire to measure various aspects of students' anxiety towards learning SPSS, the SAQ. I generated questions based on interviews with anxious and non-anxious students and came up with 23 possible questions to include. Each question was a statement followed by a five-point Likert scale: `strongly disagree', `disagree', `neither agree nor disagree', `agree' and `strongly agree' (SD, D, N, A and SA, respectively). What's more, I wanted to know whether anxiety about SPSS could be broken down into specific forms of anxiety. In other words, what latent variables contribute to anxiety about SPSS? With a little help from a few lecturer friends I collected 2571 completed questionnaires.''

\hypertarget{results-overview}{%
\subsection{Results Overview}\label{results-overview}}

\begin{table}

\caption{\label{tab:unnamed-chunk-116}Result Overview Exploratory Factor Analysis}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
  & JASP & SPSS & SAS & Minitab & R\\
\midrule
SS Loading (Factor1) & 3.0336 & 3.033 & 3.034 & NA & 3.03\\
SS Loading (Factor2) & 2.8545 & 2.855 & 2.855 & NA & 2.85\\
SS Loading (Factor3) & 1.9859 & 1.986 & 1.986 & NA & 1.99\\
SS Loading (Factor4) & 1.4351 & 1.435 & 1.435 & NA & 1.44\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{jasp}{%
\subsection{JASP}\label{jasp}}

\begin{figure}[!h]
\includegraphics{Screenshots/Principal Component Analysis/pcaJASPissue} \caption{\label{fig:pcaJASP}JASP Output for Principal Component Analysis}\label{fig:pcaJASP}
\end{figure}

\hypertarget{spss}{%
\subsection{SPSS}\label{spss}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{FACTOR}
  \OperatorTok{/}\NormalTok{VARIABLES Question_}\DecValTok{01}\NormalTok{ Question_}\DecValTok{02}\NormalTok{ Question_}\DecValTok{03}\NormalTok{ Question_}\DecValTok{04}\NormalTok{ Question_}\DecValTok{05}\NormalTok{ Question_}\DecValTok{06}\NormalTok{ Question_}\DecValTok{07} 
\NormalTok{    Question_}\DecValTok{08}\NormalTok{ Question_}\DecValTok{09}\NormalTok{ Question_}\DecValTok{10}\NormalTok{ Question_}\DecValTok{11}\NormalTok{ Question_}\DecValTok{12}\NormalTok{ Question_}\DecValTok{13}\NormalTok{ Question_}\DecValTok{14}\NormalTok{ Question_}\DecValTok{15} 
\NormalTok{    Question_}\DecValTok{16}\NormalTok{ Question_}\DecValTok{17}\NormalTok{ Question_}\DecValTok{18}\NormalTok{ Question_}\DecValTok{19}\NormalTok{ Question_}\DecValTok{20}\NormalTok{ Question_}\DecValTok{21}\NormalTok{ Question_}\DecValTok{22}\NormalTok{ Question_}\DecValTok{23}
  \OperatorTok{/}\NormalTok{MISSING LISTWISE }
  \OperatorTok{/}\NormalTok{ANALYSIS Question_}\DecValTok{01}\NormalTok{ Question_}\DecValTok{02}\NormalTok{ Question_}\DecValTok{03}\NormalTok{ Question_}\DecValTok{04}\NormalTok{ Question_}\DecValTok{05}\NormalTok{ Question_}\DecValTok{06}\NormalTok{ Question_}\DecValTok{07} 
\NormalTok{    Question_}\DecValTok{08}\NormalTok{ Question_}\DecValTok{09}\NormalTok{ Question_}\DecValTok{10}\NormalTok{ Question_}\DecValTok{11}\NormalTok{ Question_}\DecValTok{12}\NormalTok{ Question_}\DecValTok{13}\NormalTok{ Question_}\DecValTok{14}\NormalTok{ Question_}\DecValTok{15} 
\NormalTok{    Question_}\DecValTok{16}\NormalTok{ Question_}\DecValTok{17}\NormalTok{ Question_}\DecValTok{18}\NormalTok{ Question_}\DecValTok{19}\NormalTok{ Question_}\DecValTok{20}\NormalTok{ Question_}\DecValTok{21}\NormalTok{ Question_}\DecValTok{22}\NormalTok{ Question_}\DecValTok{23}
  \OperatorTok{/}\NormalTok{PRINT INITIAL ROTATION}
  \OperatorTok{/}\NormalTok{PLOT EIGEN}
  \OperatorTok{/}\NormalTok{CRITERIA }\KeywordTok{MINEIGEN}\NormalTok{(}\DecValTok{1}\NormalTok{) }\KeywordTok{ITERATE}\NormalTok{(}\DecValTok{25}\NormalTok{)}
  \OperatorTok{/}\NormalTok{EXTRACTION PC}
  \OperatorTok{/}\NormalTok{CRITERIA }\KeywordTok{ITERATE}\NormalTok{(}\DecValTok{25}\NormalTok{)}
  \OperatorTok{/}\NormalTok{ROTATION VARIMAX}
  \OperatorTok{/}\NormalTok{METHOD=CORRELATION.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Principal Component Analysis/pcaSPSS1} \caption{\label{fig:pcaSPSS}SPSS Output for Principal Component Analysis}\label{fig:pcaSPSS}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Principal Component Analysis/pcaSPSS2} \caption{\label{fig:pcaSPSS}SPSS Output for Principal Component Analysis}\label{fig:pcaSPSS2}
\end{figure}

\hypertarget{sas}{%
\subsection{SAS}\label{sas}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC FACTOR Data=work.PCA scree}
\NormalTok{		Nfactors=}\StringTok{ }\DecValTok{4}
\NormalTok{		Method=}\StringTok{ }\NormalTok{p}
\NormalTok{		Rotate=varimax;}
\NormalTok{		Var Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9 Q10 Q11 Q12 Q13 Q14 Q15 Q16 Q17 Q18 Q19 Q20 Q21 Q22 Q23}
\NormalTok{		; }
\NormalTok{		Run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Principal Component Analysis/pcaSAS1} \caption{\label{fig:pcaSAS}SAS Output for Principal Component Analysis}\label{fig:pcaSAS}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Principal Component Analysis/pcaSAS2} \caption{\label{fig:pcaSAS}SAS Output for Principal Component Analysis}\label{fig:pcaSAS2}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Principal Component Analysis/pcaSAS3} \caption{\label{fig:pcaSAS}SAS Output for Principal Component Analysis}\label{fig:pcaSAS3}
\end{figure}

\hypertarget{minitab}{%
\subsection{Minitab}\label{minitab}}

\begin{figure}[!h]
\includegraphics{Screenshots/Principal Component Analysis/pcaMinitab1} \caption{\label{fig:pcaMinitab}Minitab Output for Principal Component Analysis}\label{fig:pcaMinitab}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Principal Component Analysis/pcaMinitab2} \caption{\label{fig:pcaMinitab}Minitab Output for Principal Component Analysis}\label{fig:pcaMinitab2}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Principal Component Analysis/pcaMinitab3} \caption{\label{fig:pcaMinitab}Minitab Output for Principal Component Analysis}\label{fig:pcaMinitab3}
\end{figure}

\hypertarget{r}{%
\subsection{R}\label{r}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{## install.packages("psych")}
\CommentTok{## install.packages("factoextra")}
\CommentTok{## Principal Component Analysis}
\KeywordTok{library}\NormalTok{(}\StringTok{"psych"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'psych'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:car':
## 
##     logit
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(}\StringTok{"factoextra"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: ggplot2
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'ggplot2'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:psych':
## 
##     %+%, alpha
\end{verbatim}

\begin{verbatim}
## Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit1 <-}\StringTok{ }\KeywordTok{prcomp}\NormalTok{(PCA.data, }\DataTypeTok{scale =} \OtherTok{TRUE}\NormalTok{) }\CommentTok{#eigenvalues}
\NormalTok{eig.val <-}\StringTok{ }\KeywordTok{get_eigenvalue}\NormalTok{(fit1)}
\NormalTok{eig.val }\CommentTok{## print results}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        eigenvalue variance.percent cumulative.variance.percent
## Dim.1   7.2900471        31.695857                    31.69586
## Dim.2   1.7388287         7.560125                    39.25598
## Dim.3   1.3167515         5.725007                    44.98099
## Dim.4   1.2271982         5.335644                    50.31663
## Dim.5   0.9878779         4.295121                    54.61175
## Dim.6   0.8953304         3.892741                    58.50449
## Dim.7   0.8055604         3.502436                    62.00693
## Dim.8   0.7828199         3.403565                    65.41050
## Dim.9   0.7509712         3.265092                    68.67559
## Dim.10  0.7169577         3.117207                    71.79280
## Dim.11  0.6835877         2.972121                    74.76492
## Dim.12  0.6695016         2.910876                    77.67579
## Dim.13  0.6119976         2.660859                    80.33665
## Dim.14  0.5777377         2.511903                    82.84855
## Dim.15  0.5491875         2.387772                    85.23633
## Dim.16  0.5231504         2.274567                    87.51089
## Dim.17  0.5083962         2.210418                    89.72131
## Dim.18  0.4559399         1.982347                    91.70366
## Dim.19  0.4238036         1.842624                    93.54628
## Dim.20  0.4077909         1.773004                    95.31929
## Dim.21  0.3794799         1.649912                    96.96920
## Dim.22  0.3640223         1.582705                    98.55191
## Dim.23  0.3330618         1.448095                   100.00000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{fviz_eig}\NormalTok{(fit1) }\CommentTok{#scree plot}
\end{Highlighting}
\end{Shaded}

\includegraphics{Verification-Project-JASP_files/figure-latex/unnamed-chunk-120-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit2 <-}\StringTok{ }\KeywordTok{principal}\NormalTok{(PCA.data, }\DataTypeTok{nfactors=}\DecValTok{4}\NormalTok{, }\DataTypeTok{rotate =} \StringTok{"varimax"}\NormalTok{) }\CommentTok{#varimax rotiation}
\NormalTok{fit2 }\CommentTok{## print results}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Principal Components Analysis
## Call: principal(r = PCA.data, nfactors = 4, rotate = "varimax")
## Standardized loadings (pattern matrix) based upon correlation matrix
##                  RC3   RC1   RC4   RC2   h2   u2 com
## ï..Question_01  0.24  0.50  0.36  0.06 0.43 0.57 2.4
## Question_02    -0.01 -0.34  0.07  0.54 0.41 0.59 1.7
## Question_03    -0.20 -0.57 -0.18  0.37 0.53 0.47 2.3
## Question_04     0.32  0.52  0.31  0.04 0.47 0.53 2.4
## Question_05     0.32  0.43  0.24  0.01 0.34 0.66 2.5
## Question_06     0.80 -0.01  0.10 -0.07 0.65 0.35 1.0
## Question_07     0.64  0.33  0.16 -0.08 0.55 0.45 1.7
## Question_08     0.13  0.17  0.83  0.01 0.74 0.26 1.1
## Question_09    -0.09 -0.20  0.12  0.65 0.48 0.52 1.3
## Question_10     0.55  0.00  0.13 -0.12 0.33 0.67 1.2
## Question_11     0.26  0.21  0.75 -0.14 0.69 0.31 1.5
## Question_12     0.47  0.52  0.09 -0.08 0.51 0.49 2.1
## Question_13     0.65  0.23  0.23 -0.10 0.54 0.46 1.6
## Question_14     0.58  0.36  0.14 -0.07 0.49 0.51 1.8
## Question_15     0.46  0.22  0.29 -0.19 0.38 0.62 2.6
## Question_16     0.33  0.51  0.31 -0.12 0.49 0.51 2.6
## Question_17     0.27  0.22  0.75 -0.04 0.68 0.32 1.5
## Question_18     0.68  0.33  0.13 -0.08 0.60 0.40 1.5
## Question_19    -0.15 -0.37 -0.03  0.43 0.34 0.66 2.2
## Question_20    -0.04  0.68  0.07 -0.14 0.48 0.52 1.1
## Question_21     0.29  0.66  0.16 -0.07 0.55 0.45 1.5
## Question_22    -0.19  0.03 -0.10  0.65 0.46 0.54 1.2
## Question_23    -0.02  0.17 -0.20  0.59 0.41 0.59 1.4
## 
##                        RC3  RC1  RC4  RC2
## SS loadings           3.73 3.34 2.55 1.95
## Proportion Var        0.16 0.15 0.11 0.08
## Cumulative Var        0.16 0.31 0.42 0.50
## Proportion Explained  0.32 0.29 0.22 0.17
## Cumulative Proportion 0.32 0.61 0.83 1.00
## 
## Mean item complexity =  1.8
## Test of the hypothesis that 4 components are sufficient.
## 
## The root mean square of the residuals (RMSR) is  0.06 
##  with the empirical chi square  4006.15  with prob <  0 
## 
## Fit based upon off diagonal values = 0.96
\end{verbatim}

\hypertarget{remarks}{%
\subsection{Remarks}\label{remarks}}

The rotation used was ``Varimax''. All differences in results between the software are due to rounding.

\hypertarget{references}{%
\subsection{References}\label{references}}

Field, A. (2018). \emph{Discovering statistics using IBM SPSS statistics}. Los Angeles, CA: SAGE.

\hypertarget{exploratory-factor-analysis}{%
\section{Exploratory Factor Analysis}\label{exploratory-factor-analysis}}

An example from Field (2018 pp.~795-796):

``I have noticed that a lot of students become very stressed about SPSS Statistics. Imagine that I wanted to design a questionnaire to measure a trait that I termed `SPSS anxiety'. I devised a questionnaire to measure various aspects of students' anxiety towards learning SPSS, the SAQ. I generated questions based on interviews with anxious and non-anxious students and came up with 23 possible questions to include. Each question was a statement followed by a five-point Likert scale: `strongly disagree', `disagree', `neither agree nor disagree', `agree' and `strongly agree' (SD, D, N, A and SA, respectively). What's more, I wanted to know whether anxiety about SPSS could be broken down into specific forms of anxiety. In other words, what latent variables contribute to anxiety about SPSS? With a little help from a few lecturer friends I collected 2571 completed questionnaires.''

\hypertarget{results-overview-1}{%
\subsection{Results Overview}\label{results-overview-1}}

\begin{table}

\caption{\label{tab:unnamed-chunk-121}Result Overview Exploratory Factor Analysis}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
  & JASP & SPSS & SAS & Minitab & R\\
\midrule
SS Loading (Factor1) & 3.0336 & 3.033 & 3.034 & NA & 3.03\\
SS Loading (Factor2) & 2.8545 & 2.855 & 2.855 & NA & 2.85\\
SS Loading (Factor3) & 1.9859 & 1.986 & 1.986 & NA & 1.99\\
SS Loading (Factor4) & 1.4351 & 1.435 & 1.435 & NA & 1.44\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{jasp-1}{%
\subsection{JASP}\label{jasp-1}}

\begin{figure}[!h]
\includegraphics{Screenshots/Exploratory Factor Analysis/efaJASP1} \caption{\label{fig:efaJASP}JASP Output for Exploratory Factor Analysis}\label{fig:efaJASP}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Exploratory Factor Analysis/efaJASP2} \caption{\label{fig:efaJASP2}JASP Output for Exploratory Factor Analysis}\label{fig:efaJASP2}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Exploratory Factor Analysis/efaJASP3} \caption{\label{fig:efaJASP3}JASP Output for Exploratory Factor Analysis}\label{fig:efaJASP3}
\end{figure}

\hypertarget{spss-1}{%
\subsection{SPSS}\label{spss-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{FACTOR}
  \OperatorTok{/}\NormalTok{VARIABLES Question_}\DecValTok{01}\NormalTok{ Question_}\DecValTok{02}\NormalTok{ Question_}\DecValTok{03}\NormalTok{ Question_}\DecValTok{04}\NormalTok{ Question_}\DecValTok{05}\NormalTok{ Question_}\DecValTok{06}\NormalTok{ Question_}\DecValTok{07} 
\NormalTok{    Question_}\DecValTok{08}\NormalTok{ Question_}\DecValTok{09}\NormalTok{ Question_}\DecValTok{10}\NormalTok{ Question_}\DecValTok{11}\NormalTok{ Question_}\DecValTok{12}\NormalTok{ Question_}\DecValTok{13}\NormalTok{ Question_}\DecValTok{14}\NormalTok{ Question_}\DecValTok{15} 
\NormalTok{    Question_}\DecValTok{16}\NormalTok{ Question_}\DecValTok{17}\NormalTok{ Question_}\DecValTok{18}\NormalTok{ Question_}\DecValTok{19}\NormalTok{ Question_}\DecValTok{20}\NormalTok{ Question_}\DecValTok{21}\NormalTok{ Question_}\DecValTok{22}\NormalTok{ Question_}\DecValTok{23}
  \OperatorTok{/}\NormalTok{MISSING LISTWISE }
  \OperatorTok{/}\NormalTok{ANALYSIS Question_}\DecValTok{01}\NormalTok{ Question_}\DecValTok{02}\NormalTok{ Question_}\DecValTok{03}\NormalTok{ Question_}\DecValTok{04}\NormalTok{ Question_}\DecValTok{05}\NormalTok{ Question_}\DecValTok{06}\NormalTok{ Question_}\DecValTok{07} 
\NormalTok{    Question_}\DecValTok{08}\NormalTok{ Question_}\DecValTok{09}\NormalTok{ Question_}\DecValTok{10}\NormalTok{ Question_}\DecValTok{11}\NormalTok{ Question_}\DecValTok{12}\NormalTok{ Question_}\DecValTok{13}\NormalTok{ Question_}\DecValTok{14}\NormalTok{ Question_}\DecValTok{15} 
\NormalTok{    Question_}\DecValTok{16}\NormalTok{ Question_}\DecValTok{17}\NormalTok{ Question_}\DecValTok{18}\NormalTok{ Question_}\DecValTok{19}\NormalTok{ Question_}\DecValTok{20}\NormalTok{ Question_}\DecValTok{21}\NormalTok{ Question_}\DecValTok{22}\NormalTok{ Question_}\DecValTok{23}
  \OperatorTok{/}\NormalTok{PRINT INITIAL KMO EXTRACTION ROTATION}
  \OperatorTok{/}\NormalTok{CRITERIA }\KeywordTok{MINEIGEN}\NormalTok{(}\DecValTok{1}\NormalTok{) }\KeywordTok{ITERATE}\NormalTok{(}\DecValTok{25}\NormalTok{)}
  \OperatorTok{/}\NormalTok{EXTRACTION PAF}
  \OperatorTok{/}\NormalTok{CRITERIA }\KeywordTok{ITERATE}\NormalTok{(}\DecValTok{25}\NormalTok{)}
  \OperatorTok{/}\NormalTok{ROTATION VARIMAX}
  \OperatorTok{/}\NormalTok{METHOD=CORRELATION.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Exploratory Factor Analysis/efaSPSS1} \caption{\label{fig:efaSPSS}SPSS Output for Exploratory Factor Analysis}\label{fig:efaSPSS}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Exploratory Factor Analysis/efaSPSS2} \caption{\label{fig:efaSPSS2}SPSS Output for Exploratory Factor Analysis}\label{fig:efaSPSS2}
\end{figure}

\hypertarget{sas-1}{%
\subsection{SAS}\label{sas-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC FACTOR Data=work.efa scree}
\NormalTok{		Nfactors=}\StringTok{ }\DecValTok{4}
\NormalTok{		Method=}\StringTok{ }\NormalTok{prinit}
\NormalTok{		Rotate=varimax;}
\NormalTok{		Var Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9 Q10 Q11 Q12 Q13 Q14 Q15 Q16 Q17 Q18 Q19 Q20 Q21 Q22 Q23}
\NormalTok{		; }
\NormalTok{		Run;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Exploratory Factor Analysis/efaSAS1} \caption{\label{fig:efaSAS}SAS Output for Exploratory Factor Analysis}\label{fig:efaSAS}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Exploratory Factor Analysis/efaSAS2} \caption{\label{fig:efaSAS2}SAS Output for Exploratory Factor Analysis}\label{fig:efaSAS2}
\end{figure}

\hypertarget{minitab-1}{%
\subsection{Minitab}\label{minitab-1}}

Exploratory Factor Analysis with Principal Axis Factoring is not available in Minitab.

\hypertarget{r-1}{%
\subsection{R}\label{r-1}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{## install.packages("psych")}
\CommentTok{## Principal Axis Factor Analysis}
\KeywordTok{library}\NormalTok{(}\StringTok{"psych"}\NormalTok{)}
\NormalTok{fit <-}\StringTok{ }\KeywordTok{factor.pa}\NormalTok{(EFA.data, }\DataTypeTok{nfactors=}\DecValTok{4}\NormalTok{, }\DataTypeTok{rotate =} \StringTok{"varimax"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: factor.pa is deprecated. Please use the fa function with fm=pa
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit }\CommentTok{## print results}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Factor Analysis using method =  pa
## Call: factor.pa(r = EFA.data, nfactors = 4, rotate = "varimax")
## Unstandardized loadings (pattern matrix) based upon covariance matrix
##                  PA1   PA3   PA4   PA2   h2   u2   H2   U2
## ï..Question_01  0.50  0.22 -0.27  0.00 0.37 0.63 0.37 0.63
## Question_02    -0.21 -0.03 -0.01  0.46 0.26 0.74 0.26 0.74
## Question_03    -0.50 -0.18  0.16  0.40 0.47 0.53 0.47 0.53
## Question_04     0.53  0.28 -0.25 -0.03 0.42 0.58 0.42 0.58
## Question_05     0.44  0.27 -0.19 -0.05 0.30 0.70 0.30 0.70
## Question_06     0.05  0.75 -0.12 -0.10 0.59 0.41 0.59 0.41
## Question_07     0.36  0.56 -0.16 -0.13 0.49 0.51 0.49 0.51
## Question_08     0.22  0.15 -0.76  0.00 0.65 0.35 0.65 0.35
## Question_09    -0.13 -0.07 -0.06  0.56 0.34 0.66 0.34 0.66
## Question_10     0.14  0.38 -0.14 -0.12 0.20 0.80 0.20 0.80
## Question_11     0.24  0.27 -0.69 -0.17 0.63 0.37 0.63 0.37
## Question_12     0.51  0.40 -0.11 -0.15 0.45 0.55 0.45 0.55
## Question_13     0.29  0.56 -0.23 -0.14 0.47 0.53 0.47 0.53
## Question_14     0.39  0.49 -0.15 -0.13 0.42 0.58 0.42 0.58
## Question_15     0.28  0.38 -0.25 -0.20 0.32 0.68 0.32 0.68
## Question_16     0.54  0.28 -0.25 -0.16 0.46 0.54 0.46 0.54
## Question_17     0.29  0.27 -0.64 -0.05 0.58 0.42 0.58 0.42
## Question_18     0.37  0.61 -0.14 -0.13 0.54 0.46 0.54 0.46
## Question_19    -0.28 -0.15  0.06  0.38 0.24 0.76 0.24 0.76
## Question_20     0.46  0.04 -0.09 -0.20 0.27 0.73 0.27 0.73
## Question_21     0.59  0.26 -0.15 -0.15 0.47 0.53 0.47 0.53
## Question_22    -0.03 -0.16  0.07  0.47 0.25 0.75 0.25 0.75
## Question_23     0.03 -0.04  0.07  0.33 0.12 0.88 0.12 0.88
## 
##                        PA1  PA3  PA4  PA2
## SS loadings           3.03 2.85 1.99 1.44
## Proportion Var        0.13 0.12 0.09 0.06
## Cumulative Var        0.13 0.26 0.34 0.40
## Proportion Explained  0.33 0.31 0.21 0.15
## Cumulative Proportion 0.33 0.63 0.85 1.00
## 
##  Standardized loadings (pattern matrix)
##                item   PA1   PA3   PA4   PA2   h2   u2
## ï..Question_01    1  0.50  0.22 -0.27  0.00 0.37 0.63
## Question_02       2 -0.21 -0.03 -0.01  0.46 0.26 0.74
## Question_03       3 -0.50 -0.18  0.16  0.40 0.47 0.53
## Question_04       4  0.53  0.28 -0.25 -0.03 0.42 0.58
## Question_05       5  0.44  0.27 -0.19 -0.05 0.30 0.70
## Question_06       6  0.05  0.75 -0.12 -0.10 0.59 0.41
## Question_07       7  0.36  0.56 -0.16 -0.13 0.49 0.51
## Question_08       8  0.22  0.15 -0.76  0.00 0.65 0.35
## Question_09       9 -0.13 -0.07 -0.06  0.56 0.34 0.66
## Question_10      10  0.14  0.38 -0.14 -0.12 0.20 0.80
## Question_11      11  0.24  0.27 -0.69 -0.17 0.63 0.37
## Question_12      12  0.51  0.40 -0.11 -0.15 0.45 0.55
## Question_13      13  0.29  0.56 -0.23 -0.14 0.47 0.53
## Question_14      14  0.39  0.48 -0.15 -0.13 0.42 0.58
## Question_15      15  0.28  0.38 -0.25 -0.20 0.32 0.68
## Question_16      16  0.54  0.28 -0.25 -0.16 0.46 0.54
## Question_17      17  0.30  0.27 -0.64 -0.05 0.58 0.42
## Question_18      18  0.37  0.61 -0.14 -0.13 0.54 0.46
## Question_19      19 -0.28 -0.15  0.06  0.37 0.24 0.76
## Question_20      20  0.47  0.04 -0.09 -0.20 0.27 0.73
## Question_21      21  0.60  0.26 -0.15 -0.15 0.47 0.53
## Question_22      22 -0.03 -0.16  0.07  0.47 0.25 0.75
## Question_23      23  0.03 -0.04  0.07  0.33 0.12 0.88
## 
##                  PA1  PA3  PA4  PA2
## SS loadings     3.03 2.85 1.99 1.44
## Proportion Var  0.13 0.12 0.09 0.06
## Cumulative Var  0.13 0.26 0.34 0.40
## Cum. factor Var 0.33 0.63 0.85 1.00
## 
## Mean item complexity =  1.8
## Test of the hypothesis that 4 factors are sufficient.
## 
## The degrees of freedom for the null model are  253  and the objective function was  7.55 with Chi Square of  19334.49
## The degrees of freedom for the model are 167  and the objective function was  0.46 
## 
## The root mean square of the residuals (RMSR) is  0.03 
## The df corrected root mean square of the residuals is  0.03 
## 
## The harmonic number of observations is  2571 with the empirical chi square  880.48  with prob <  2.3e-97 
## The total number of observations was  2571  with Likelihood Chi Square =  1166.49  with prob <  2.1e-149 
## 
## Tucker Lewis Index of factoring reliability =  0.921
## RMSEA index =  0.048  and the 90 % confidence intervals are  0.046 0.051
## BIC =  -144.8
## Fit based upon off diagonal values = 0.99
## Measures of factor score adequacy             
##                                                    PA1  PA3  PA4  PA2
## Correlation of (regression) scores with factors   0.83 0.86 0.86 0.77
## Multiple R square of scores with factors          0.69 0.73 0.74 0.59
## Minimum correlation of possible factor scores     0.37 0.46 0.49 0.19
\end{verbatim}

\hypertarget{remarks-1}{%
\subsection{Remarks}\label{remarks-1}}

The method used was ``Principal Axis Factoring'' and the rotation used was ``Varimax''. All differences in results between the software are due to rounding.

\hypertarget{references-1}{%
\subsection{References}\label{references-1}}

Field, A. (2018). \emph{Discovering statistics using IBM SPSS statistics}. Los Angeles, CA: SAGE.

\hypertarget{reliability-module}{%
\chapter{Reliability Module}\label{reliability-module}}

\hypertarget{classical-single-test-reliability-analysis}{%
\section{Classical Single-Test Reliability Analysis}\label{classical-single-test-reliability-analysis}}

An example from Field (2018 pp.~795-796):

``I have noticed that a lot of students become very stressed about SPSS Statistics. Imagine that I wanted to design a questionnaire to measure a trait that I termed `SPSS anxiety'. I devised a questionnaire to measure various aspects of students' anxiety towards learning SPSS, the SAQ. I generated questions based on interviews with anxious and non-anxious students and came up with 23 possible questions to include. Each question was a statement followed by a five-point Likert scale: `strongly disagree', `disagree', `neither agree nor disagree', `agree' and `strongly agree' (SD, D, N, A and SA, respectively). What's more, I wanted to know whether anxiety about SPSS could be broken down into specific forms of anxiety. In other words, what latent variables contribute to anxiety about SPSS? With a little help from a few lecturer friends I collected 2571 completed questionnaires.''

\textbf{Note:} Only questions 1, 4, 5, 6, 7, 8, and 10 have been used to simplify the analysis.

\hypertarget{results-overview}{%
\subsection{Results Overview}\label{results-overview}}

\begin{table}

\caption{\label{tab:unnamed-chunk-126}Result Overview Reliability Analysis}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
  & JASP & SPSS & SAS & Minitab & R\\
\midrule
Cronbachs \$\textbackslash{}alpha\$ & 0.7574 & 0.758 & 0.7574 & 0.7574 & 0.7574\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{jasp}{%
\subsection{JASP}\label{jasp}}

\begin{figure}[!h]
\includegraphics{Screenshots/Reliability/ReliabilityJASP} \caption{\label{fig:reliJASP}JASP Output for Reliability Analysis}\label{fig:reliJASP}
\end{figure}

\hypertarget{spss}{%
\subsection{SPSS}\label{spss}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DATASET ACTIVATE DataSet1.}
\NormalTok{RELIABILITY}
  \OperatorTok{/}\NormalTok{VARIABLES=Question_}\DecValTok{01}\NormalTok{ Question_}\DecValTok{04}\NormalTok{ Question_}\DecValTok{05}\NormalTok{ Question_}\DecValTok{06}\NormalTok{ Question_}\DecValTok{07}\NormalTok{ Question_}\DecValTok{08}\NormalTok{ Question_}\DecValTok{10}
  \OperatorTok{/}\KeywordTok{SCALE}\NormalTok{(}\StringTok{'ALL VARIABLES'}\NormalTok{) ALL}
  \OperatorTok{/}\NormalTok{MODEL=ALPHA}
  \OperatorTok{/}\NormalTok{STATISTICS=DESCRIPTIVE SCALE}
  \OperatorTok{/}\NormalTok{SUMMARY=TOTAL MEANS.}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Reliability/ReliabilitySPSS1} \caption{\label{fig:reliSPSS}SPSS Output for Reliability Analysis}\label{fig:reliSPSS}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Reliability/ReliabilitySPSS2} \caption{\label{fig:reliSPSS2}SPSS Output for Reliability Analysis}\label{fig:reliSPSS2}
\end{figure}

\hypertarget{sas}{%
\subsection{SAS}\label{sas}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROC CORR DATA=work.Reliability ALPHA;}
\NormalTok{    VAR Q1 Q4 Q5 Q6 Q7 Q8 Q10;}
\NormalTok{RUN;}
\end{Highlighting}
\end{Shaded}

\begin{figure}[!h]
\includegraphics{Screenshots/Reliability/ReliabilitySAS} \caption{\label{fig:reliSAS}SAS Output for Reliability Analysis}\label{fig:reliSAS}
\end{figure}

\hypertarget{minitab}{%
\subsection{Minitab}\label{minitab}}

\begin{figure}[!h]
\includegraphics{Screenshots/Reliability/ReliabilityMinitab1} \caption{\label{fig:reliMinitab}Minitab Output for Reliability Analysis}\label{fig:reliMinitab}
\end{figure}

\begin{figure}[!h]
\includegraphics{Screenshots/Reliability/ReliabilityMinitab2} \caption{\label{fig:reliMinitab2}Minitab Output for Reliability Analysis}\label{fig:reliMinitab2}
\end{figure}

\hypertarget{r}{%
\subsection{R}\label{r}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# library(psych)}
\NormalTok{QuestionSelection <-}\StringTok{ }\NormalTok{reli.data[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{10}\NormalTok{)]}
\NormalTok{analysis <-}\StringTok{ }\NormalTok{psych}\OperatorTok{::}\KeywordTok{alpha}\NormalTok{(QuestionSelection)}
\NormalTok{analysis}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Reliability analysis   
## Call: psych::alpha(x = QuestionSelection)
## 
##   raw_alpha std.alpha G6(smc) average_r S/N    ase mean   sd median_r
##       0.76      0.76    0.74      0.31 3.1 0.0072  2.5 0.62      0.3
## 
##  lower alpha upper     95% confidence boundaries
## 0.74 0.76 0.77 
## 
##  Reliability if an item is dropped:
##                raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
## ï..Question_01      0.73      0.72    0.70      0.30 2.6   0.0082 0.0079  0.28
## Question_04         0.71      0.71    0.69      0.29 2.5   0.0086 0.0074  0.28
## Question_05         0.72      0.72    0.70      0.30 2.6   0.0082 0.0091  0.30
## Question_06         0.73      0.73    0.70      0.31 2.7   0.0081 0.0065  0.31
## Question_07         0.70      0.71    0.68      0.29 2.4   0.0090 0.0067  0.27
## Question_08         0.74      0.74    0.72      0.32 2.9   0.0078 0.0083  0.31
## Question_10         0.75      0.75    0.73      0.34 3.0   0.0076 0.0071  0.33
## 
##  Item statistics 
##                   n raw.r std.r r.cor r.drop mean   sd
## ï..Question_01 2571  0.62  0.65  0.57   0.48  2.4 0.83
## Question_04    2571  0.68  0.69  0.63   0.54  2.8 0.95
## Question_05    2571  0.65  0.66  0.57   0.49  2.7 0.96
## Question_06    2571  0.66  0.63  0.55   0.47  2.2 1.12
## Question_07    2571  0.73  0.70  0.65   0.57  2.9 1.10
## Question_08    2571  0.57  0.59  0.47   0.41  2.2 0.87
## Question_10    2571  0.54  0.55  0.42   0.37  2.3 0.88
## 
## Non missing response frequency for each item
##                   1    2    3    4    5 miss
## ï..Question_01 0.11 0.52 0.29 0.07 0.02    0
## Question_04    0.05 0.37 0.36 0.17 0.05    0
## Question_05    0.06 0.43 0.29 0.18 0.04    0
## Question_06    0.27 0.44 0.13 0.10 0.06    0
## Question_07    0.07 0.34 0.26 0.24 0.09    0
## Question_08    0.15 0.58 0.19 0.06 0.03    0
## Question_10    0.14 0.57 0.18 0.10 0.02    0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{analysis}\OperatorTok{$}\NormalTok{total}\OperatorTok{$}\NormalTok{raw_alpha}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7573813
\end{verbatim}

\hypertarget{remarks}{%
\subsection{Remarks}\label{remarks}}

All differences in results between the software and hand calculation are due to rounding.

\hypertarget{references}{%
\subsection{References}\label{references}}

Field, A. (2018). \emph{Discovering statistics using IBM SPSS statistics}. Los Angeles, CA: SAGE.

  \bibliography{book.bib,packages.bib}

\end{document}
